### ISSUE TITLE
Multiple Leiningen install failures in Windows

### ISSUE THREAD

**Issue by mcandre** [technomancy/leiningen#1040]
Chocolatey Leiningen failed to install, so I tried `lein.bat`. But it did this:

```
C:\Users\andrew\Downloads>lein self-install
Downloading Leiningen now...

C:\Users\andrew\Downloads>lein

C:\Users\andrew\.lein\self-installs\leiningen-2.0.0-standalone.jar can not be found.
You can try running "lein self-install"
or change LEIN_JAR environment variable
or edit lein.bat to set appropriate LEIN_JAR path.
```

So I tried the `lein` shell script in a Git Bash window. It also fails. :( I just want Clojure on Windows.

Trace:

```
$ ./lein.sh
Downloading Leiningen to /c/msys/1.0/home/.lein/self-installs/leiningen-2.0.0-standalone.jar now...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.6M  100 12.6M    0     0  1341k      0  0:00:09  0:00:09 --:--:-- 1526k
Exception in thread "main" java.lang.NoClassDefFoundError: clojure/main
Caused by: java.lang.ClassNotFoundException: clojure.main
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: clojure.main.  Program will exit.
```

System:

```
$ specs git os
Specs:

specs 0.2
https://github.com/mcandre/specs#readme

git --version
git version 1.8.0.msysgit.0

systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 8 Pro
OS Version:                6.2.9200 N/A Build 9200
```

**Comment by LispyAriaro** [comment]
Another way to solve this issue is to edit the lein.bat file at: C:\Users\%%Your_Name%%\.lein\bin\ ... do Ctrl F in your text editor to find where wget is used. Simply add the --no-check-certificate after %2 like so: 
    call wget -O %1 %2 --no-check-certificate

Save the file then re-run lein self-install ... that oughta fix it.

**Comment by winks** [comment]
Related: https://github.com/technomancy/leiningen/issues/1800

We don't want the no-check workaround, but it's in progress.
