### ISSUE TITLE
Use credentials for downloading search index files

### ISSUE THREAD

**Issue by FlorianO** [technomancy/leiningen#1155]
`lein search` and all plugins based on this (e.g. outdated)are not working for repositories with credentials.
The Repository is working absolutely fine with leiningen otherwise. 
From the sourcecode it seems it only is doing a simple http/get without the credentials from the project.clj.

When i run

```
DEBUG=true lein search
```

i get the following:

```
Leiningen's classpath: :/Users/xxx/.lein/self-installs/leiningen-2.1.3-standalone.jar
Applying task search to (ring)
Updating the search index. This may take a few minutes...
Downloading http://OUR_LOCAL_REPO/nexus/content/repositories/snapshots/.index/nexus-maven-repository-index.properties
Downloading http://OUR_LOCAL_REPO/nexus/content/repositories/snapshots/.index/nexus-maven-repository-index.gz
Downloading http://OUR_LOCAL_REPO/nexus/content/repositories/snapshots/.index/nexus-maven-repository-index.zip
[ERROR] Fallback to *.zip also failed: org.apache.lucene.index.IndexNotFoundException: no segments* file found in org.apache.lucene.store.NIOFSDirectory@/Users/xxx/.lein/indices/tmp/nexus-index3780207200388538103.dir lockFactory=org.apache.lucene.store.NativeFSLockFactory@2312d07c: files: []
java.io.EOFException
    at java.io.DataInputStream.readByte(DataInputStream.java:267)
    at org.apache.maven.index.updater.IndexDataReader.readHeader(IndexDataReader.java:111)
    at org.apache.maven.index.updater.IndexDataReader.readIndex(IndexDataReader.java:76)
    at org.apache.maven.index.updater.DefaultIndexUpdater.unpackIndexData(DefaultIndexUpdater.java:509)
    at org.apache.maven.index.updater.DefaultIndexUpdater.loadIndexDirectory(DefaultIndexUpdater.java:197)
    at org.apache.maven.index.updater.DefaultIndexUpdater.access$300(DefaultIndexUpdater.java:76)
    at org.apache.maven.index.updater.DefaultIndexUpdater$LuceneIndexAdaptor.setIndexFile(DefaultIndexUpdater.java:642)
    at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:862)
    at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:157)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
    at leiningen.search$update_index.invoke(search.clj:55)
```

**Comment by shimanekb** [comment]
Are you using a certificate or any credentials for the repository?

**Comment by glts** [comment]
As far as I can see the whole search index thing was binned in #2235; if so, this issue is obsolete and can be closed.

**Comment by technomancy** [comment]
Thanks for pointing that out.
