### ISSUE TITLE
lein.bat plugin development issue below windows, refer Issue #718

### ISSUE THREAD

**Issue by sniperliu** [technomancy/leiningen#1420]
Hi,
I found there still have problem with lein.bat with .lein-classpath under windows.
OS: Windows Vista
Editor: Light Table

.lein-class
..\myplugin\src\

Error:
Exception in thread "main" java.lang.NoClassDefFoundError: ;C:\Users\LiuHao\Programs\leiningen\self-installs\leiningen-2/2/0-standalone/
Caused by: java.lang.ClassNotFoundException: ;C:\Users\LiuHao\Programs\leiningen\self-installs\leiningen-2.2.0-standalone.jar
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: ;C:\Users\LiuHao\Programs\leiningen\self-installs\leiningen-2.2.0-standalone.jar.  Program will exit.

The error is caused by trailing space from classpath, but I am not sure where it come from.

Suggest change, just trim the string:
from 
for /f %%i in (".lein-classpath") do set CONTEXT_CP=%%i 
to
for /f "tokens=* delims= " %%i in (.lein-classpath) do set CONTEXT_CP=%%i

**Comment by winks** [comment]
Hmm, I am not so sure I agree with this, but I am far from an expert in batch stuff.

I wrote this little reproduce script (obviously, `c:\apps\.lein-classpath` must exist):

`c:\apps\bin\asdf.bat`:
```
@echo off

echo "%~dp0"
echo "%~dp0..\.lein-classpath"
echo "---"
if exist "%~dp0..\.lein-classpath" (
    for /f %%i in ("%~dp0..\.lein-classpath ") do (
        echo "%%i"y
        set CONTEXT_CP=%%i
        echo "%CONTEXT_CP%"y
    )
    echo 42
    for /f "tokens=* delims= " %%i in ("%~dp0..\.lein-classpath ") do (
        echo "%%i"x
        set CONTEXT_CP2=%%i
        echo "%CONTEXT_CP2%"x
    )
    if NOT "x!CONTEXT_CP!"=="x" (
        set CLASSPATH=!CONTEXT_CP!;!CLASSPATH!
    )
)
echo "---"
```

which outputs:
```
"c:\Apps\bin\"
"c:\Apps\bin\..\.lein-classpath"
"---"
"c:\Apps\bin\..\.lein-classpath"y
"c:\Apps\bin\..\.lein-classpath"y
42
"c:\Apps\bin\..\.lein-classpath "x
"c:\Apps\bin\..\.lein-classpath "x
"---"
```

So for the case of having a space inside the " it makes it worse.
Maybe that's a contrived example, but I couldn't reproduce your original case
