### ISSUE TITLE
:profiles :dev :source-paths ["dev"] breaks java compilation

### ISSUE THREAD

**Issue by paulrd** [technomancy/leiningen#1477]
Strange behavior:

create a project:

``` clojure
(defproject mdg/meat2 "0.1.0-SNAPSHOT"
  :main mdg.meat2
  :java-source-paths ["java"]
  :dependencies [[org.clojure/clojure "1.5.1"]]
  :profiles {:dev {:source-paths ["dev"]}}
  )
```

Put user.clj in the dev folder:

``` clojure
(ns user
  (:require [mdg.meat2]))
```

Put meat2.clj in src/mdg/meat2.clj:

``` clojure
(ns mdg.meat2
  (:import TestClass))

(defn -main [& args]
  (println "Hello world!")
  (TestClass.))

```

java source in java folder

``` java
public class TestClass {
  public TestClass() {
    System.out.println("I don't do a whole lot.");
  }
}
```

```
lein clean && lein run

Exception in thread "main" java.lang.ExceptionInInitializerError
    at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.ClassNotFoundException: TestClass
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:190)
    at mdg.meat2$eval9$loading__4910__auto____10.invoke(meat2.clj:1)
    at mdg.meat2$eval9.invoke(meat2.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6608)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.load(RT.java:440)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5018.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5336)
    at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
    at clojure.core$load_lib.doInvoke(core.clj:5374)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5413)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$require.doInvoke(core.clj:5496)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at user$eval3$loading__4910__auto____4.invoke(user.clj:1)
    at user$eval3.invoke(user.clj:1)
```

Remove the :dev profile and everything runs fine. lein javac gives the same error.

**Comment by smoosh911** [comment]
Was this issue resolved? I'm having the same problem myself. What @technomancy described is exactly what is happening to me.

**Comment by vemv** [comment]
user.clj is sort of a delicate mechanism, personally I don't use it at all - repeated issues in various tooling over the years have hinted that it's a sensible thing to do.

One can always name this file `dev.clj` instead, and rely less on compiler intricacies for getting a dev setup working.

Lein accepts a `:repl-options {:init-ns dev}` option.

**Comment by faisalhasnain** [comment]
@vemv thanks, that was good workaround :)
