### ISSUE TITLE
'Lein search' never completes rebuilding the search index

### ISSUE THREAD

**Issue by jjl** [technomancy/leiningen#1515]
I've left it for about half an hour and then killed it manually.

lein version: `Leiningen 2.3.3 on Java 1.7.0_45 Java HotSpot(TM) 64-Bit Server VM`
OS: OSX (through homebrew)

**Comment by deas** [comment]
I am seeing a somewhat similar issue on Linux today. Leinigen 2.6.1 on 1.8.0_03-Ubuntu-8u77-b03-3ubuntu3-b03 - on two machines. Removing the index files does not help.
`
➜  ~ lein search lein-template
Updating the search index. This may take a few minutes...
Downloading https://repo1.maven.org/maven2/.index/nexus-maven-repository-index.properties
100.0% complete
Downloading https://repo1.maven.org/maven2/.index/nexus-maven-repository-index.gz
100.0% complete
Updating the search index. This may take a few minutes...
Downloading https://clojars.org/repo/.index/nexus-maven-repository-index.properties
2016-05-02 18:56:35
Full thread dump OpenJDK 64-Bit Server VM (25.03-b03 mixed mode):

"Index-BottleWarmer-clojars" #13 daemon prio=5 os_prio=0 tid=0x00007fc4c06d6800 nid=0x63c0 waiting on condition [0x00007fc47444d000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at org.apache.maven.index.context.DefaultIndexingContext$1.run(DefaultIndexingContext.java:1189)
        at java.lang.Thread.run(Thread.java:745)

"Index-BottleWarmer-central" #12 daemon prio=5 os_prio=0 tid=0x00007fc4c06d3800 nid=0x63bf waiting on condition [0x00007fc47454e000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at org.apache.maven.index.context.DefaultIndexingContext$1.run(DefaultIndexingContext.java:1189)
        at java.lang.Thread.run(Thread.java:745)

"com.google.inject.internal.util.$Finalizer" #11 daemon prio=5 os_prio=0 tid=0x00007fc4c0663800 nid=0x63bd in Object.wait() [0x00007fc49472c000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000005cb61ff98> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        - locked <0x00000005cb61ff98> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at com.google.inject.internal.util.$Finalizer.run(Finalizer.java:143)
        at java.lang.Thread.run(Thread.java:745)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x00007fc4c00ca000 nid=0x63bb runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=0 tid=0x00007fc4c00bd000 nid=0x63ba waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007fc4c00b8800 nid=0x63b9 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007fc4c00b6800 nid=0x63b8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007fc4c00b3800 nid=0x63b7 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007fc4c00b1800 nid=0x63b6 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007fc4c008a000 nid=0x63b5 in Object.wait() [0x00007fc496ae2000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000005caa1eb38> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        - locked <0x00000005caa1eb38> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007fc4c0085800 nid=0x63b4 in Object.wait() [0x00007fc496be3000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000005caa06e08> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        - locked <0x00000005caa06e08> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=0 tid=0x00007fc4c0008000 nid=0x63aa waiting on condition [0x00007fc4c6800000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000071db55d60> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at clojure.core$promise$reify__7005.deref(core.clj:6823)
        at clojure.core$deref.invokeStatic(core.clj:2228)
        at clojure.core$deref.invoke(core.clj:2214)
        at leiningen.search$http_resource_fetcher$fn__5439.invoke(search.clj:98)
        at leiningen.search.proxy$java.lang.Object$ResourceFetcher$93824c0b.disconnect(Unknown Source)
        at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:163)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at leiningen.search$update_index.invokeStatic(search.clj:110)
        at leiningen.search$update_index.invoke(search.clj:109)
        at leiningen.search$search$fn__5504.invoke(search.clj:222)
        at leiningen.search$search.invokeStatic(search.clj:222)
        at leiningen.search$search.invoke(search.clj:193)
        at leiningen.search$search.invokeStatic(search.clj:208)
        at leiningen.search$search.invoke(search.clj:193)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$apply.invoke(core.clj:641)
        at leiningen.core.main$partial_task$fn__5829.doInvoke(main.clj:272)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$apply.invoke(core.clj:641)
        at leiningen.core.main$apply_task.invokeStatic(main.clj:322)
        at leiningen.core.main$apply_task.invoke(main.clj:308)
        at leiningen.core.main$resolve_and_apply.invokeStatic(main.clj:328)
        at leiningen.core.main$resolve_and_apply.invoke(main.clj:324)
        at leiningen.core.main$_main$fn__5895.invoke(main.clj:401)
        at leiningen.core.main$_main.invokeStatic(main.clj:394)
        at leiningen.core.main$_main.doInvoke(main.clj:391)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.main$main_opt.invokeStatic(main.clj:314)
        at clojure.main$main_opt.invoke(main.clj:310)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at clojure.lang.Var.invoke(Var.java:394)
        at clojure.lang.AFn.applyToHelper(AFn.java:165)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)

"VM Thread" os_prio=0 tid=0x00007fc4c007e000 nid=0x63b3 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007fc4c001d800 nid=0x63ab runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007fc4c001f000 nid=0x63ac runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007fc4c0021000 nid=0x63ad runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007fc4c0022800 nid=0x63ae runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00007fc4c0024800 nid=0x63af runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00007fc4c0026000 nid=0x63b0 runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00007fc4c0028000 nid=0x63b1 runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00007fc4c0029800 nid=0x63b2 runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007fc4c00d8000 nid=0x63bc waiting on condition 

JNI global references: 261

Heap
 PSYoungGen      total 118784K, used 90137K [0x0000000718e00000, 0x000000078ae80000, 0x00000007c0000000)
  eden space 114176K, 74% used [0x0000000718e00000,0x000000071e191ca8,0x000000071fd80000)
  from space 4608K, 99% used [0x000000078a080000,0x000000078a4f4850,0x000000078a500000)
  to   space 8704K, 0% used [0x000000078a600000,0x000000078a600000,0x000000078ae80000)
 ParOldGen       total 242176K, used 108114K [0x00000005caa00000, 0x00000005d9680000, 0x0000000718e00000)
  object space 242176K, 44% used [0x00000005caa00000,0x00000005d13948b0,0x00000005d9680000)
 Metaspace       used 30532K, capacity 31448K, committed 31744K, reserved 1075200K
  class space    used 5554K, capacity 5858K, committed 5888K, reserved 1048576K

`
