### ISSUE TITLE
error running lein repl

### ISSUE THREAD

**Issue by jorda0mega** [technomancy/leiningen#1580]
I have installed leiningen with OpenJDK (Windows 7 32-bit) but the moment I run lein repl on the command line I get the following error:

<pre><code>Could not transfer artifact lein-cljsbuild:cljs-compat:jar:1.0.0-20140402.162347-24 from/to clojars (https://clojars.org/repo/): peer not authenticated
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Exception in thread "main" clojure.lang.ExceptionInfo: Could not resolve dependencies {:exit-code 1, :suppress-msg true}
    at clojure.core$ex_info.invoke(core.clj:4327)
    at leiningen.core.classpath$fn__2759.invoke(classpath.clj:180)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:617)
    at clojure.core$memoize$fn__5049.doInvoke(core.clj:5735)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at leiningen.core.classpath$get_dependencies.doInvoke(classpath.clj:299)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:621)
    at leiningen.core.classpath$resolve_dependencies.doInvoke(classpath.clj:343)
    at clojure.lang.RestFn.invoke(RestFn.java:464)
    at leiningen.core.project$load_plugins.invoke(project.clj:524)
    at leiningen.core.project$load_plugins.invoke(project.clj:535)
    at leiningen.core.project$init_project.invoke(project.clj:670)
    at leiningen.light_nrepl$_main.doInvoke(light_nrepl.clj:68)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at leiningen.light_nrepl.main(Unknown Source)
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not transfer artifact lein-cljsbuild:cljs-compat:jar:1.0.0-20140402.162347-24 from/to clojars (https://clojars.org/repo/): peer not authenticated
    at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:375)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
    at cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke(aether.clj:585)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:617)
    at cemerick.pomegranate.aether$resolve_dependencies.doInvoke(aether.clj:594)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:617)
    at cemerick.pomegranate$add_dependencies.doInvoke(pomegranate.clj:74)
    at clojure.lang.RestFn.invoke(RestFn.java:2088)
    at leiningen.core.classpath$fn__2759.invoke(classpath.clj:170)
    ... 18 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not transfer artifact lein-cljsbuild:cljs-compat:jar:1.0.0-20140402.162347-24 from/to clojars (https://clojars.org/repo/): peer not authenticated
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
    at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
    ... 33 more
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact lein-cljsbuild:cljs-compat:jar:1.0.0-20140402.162347-24 from/to clojars (https://clojars.org/repo/): peer not authenticated
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:941)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
    at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.maven.wagon.TransferFailedException: peer not authenticated
    at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:892)
    at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
    at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
    at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
    ... 4 more
Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
    at sun.security.ssl.SSLSessionImpl.getPeerCertificates(Unknown Source)
    at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
    at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:746)
    at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:886)
</code></pre>

**Comment by walkermatt** [comment]
For reference I just encountered this on a fresh install of `openjdk-8-jre` on Ubuntu 15.10. Searching lead me to this [bug report](https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1396760) and the workaround post OpenJDK install to set up the certificates which is to run the following manually:

    sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure
