### ISSUE TITLE
Spark 1.2.0 dependency checksum fail

### ISSUE THREAD

**Issue by kul** [technomancy/leiningen#1802]
I suppose this is happening only with lein. For dependency `[org.apache.spark/spark-core_2.10 "1.2.0"]`, downloading jars fail with

```
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.spark:spark-core_2.10:pom:1.2.0 from/to central (https://repo1.maven.org/maven2/): Checksum validation failed, expected ./spark-core_2.10/1.2.0/spark-core_2.10-1.2.0.pom: but is bd943cf1637b461bbc63154264229b1f023b7d24
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:941)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
        at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        ... 1 more
```

**Comment by kul** [comment]
This is reproducible since 2.4.2 till master.

**Comment by hyPiRion** [comment]
This is because [their pom md5](https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.10/1.2.0/spark-core_2.10-1.2.0.pom.md5) is not an md5 checksum (well, it isn't *just* an md5 checksum, which is the problem). You should file a bug report to Apache Spark that their pom MD5 for said version is broken, so that they avoid the problem in the future.

To turn off failing during checksum checks, add this to the project map:
```clj
:checksum :warn
```

**Comment by kul** [comment]
thanks @hyPiRion .
