### ISSUE TITLE
Could not transfer artifact issue: ReasonPhrase Forbidden when lein deploy clojars

### ISSUE THREAD

**Issue by junjiemars** [technomancy/leiningen#1825]
### When I run: lein deploy clojars, got the following output:

``` clojure
Leiningen's classpath: /Users/junjie/.lein/self-installs/leiningen-2.5.1-standalone.jar
Applying task deploy to [clojars]
Wrote /Users/junjie/apps/lein-packer.git/pom.xml
Applying task javac to nil
Running javac with [@/var/folders/vz/mcsjy1jn0yx9dyvj5c512dw40000gq/T/.leiningen-cmdline1186457974010120740.tmp]
Applying task compile to nil
All namespaces already AOT compiled.
Created /Users/junjie/apps/lein-packer.git/target/lein-packer-0.1.0.jar

You need a passphrase to unlock the secret key for
user: "Junjie Mars (not dark yet) <junjiemars@gmail.com>"
4096-bit RSA key, ID C9166EA4, created 2015-02-01


You need a passphrase to unlock the secret key for
user: "Junjie Mars (not dark yet) <junjiemars@gmail.com>"
4096-bit RSA key, ID C9166EA4, created 2015-02-01

Deploying {(:extension pom.asc) /Users/junjie/apps/lein-packer.git/pom.xml.asc, (:extension jar.asc) /Users/junjie/apps/lein-packer.git/target/lein-packer-0.1.0.jar.asc, [:extension jar] /Users/junjie/apps/lein-packer.git/target/lein-packer-0.1.0.jar, [:extension pom] /Users/junjie/apps/lein-packer.git/pom.xml} to [clojars {:url https://clojars.org/repo/, :password Hw6-tdk-D8Y-PeN, :username junjiemars@gmail.com}]
Sending org/clojars/junjiemars/lein-packer/0.1.0/lein-packer-0.1.0.pom (3k)
    to https://clojars.org/repo/
Could not transfer artifact org.clojars.junjiemars:lein-packer:pom:0.1.0 from/to clojars (https://clojars.org/repo/): Access denied to: https://clojars.org/repo/org/clojars/junjiemars/lein-packer/0.1.0/lein-packer-0.1.0.pom, ReasonPhrase: Forbidden.
Sending org/clojars/junjiemars/lein-packer/0.1.0/lein-packer-0.1.0.jar (9k)
    to https://clojars.org/repo/
Sending org/clojars/junjiemars/lein-packer/0.1.0/lein-packer-0.1.0.jar.asc (1k)
    to https://clojars.org/repo/
Sending org/clojars/junjiemars/lein-packer/0.1.0/lein-packer-0.1.0.pom.asc (1k)
    to https://clojars.org/repo/
org.sonatype.aether.deployment.DeploymentException: Failed to deploy artifacts: Could not transfer artifact org.clojars.junjiemars:lein-packer:pom:0.1.0 from/to clojars (https://clojars.org/repo/): Access denied to: https://clojars.org/repo/org/clojars/junjiemars/lein-packer/0.1.0/lein-packer-0.1.0.pom, ReasonPhrase: Forbidden.
    at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:280)
    at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:211)
    at org.sonatype.aether.impl.internal.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:443)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
    at cemerick.pomegranate.aether$deploy_artifacts.doInvoke(aether.clj:338)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:624)
    at cemerick.pomegranate.aether$deploy.doInvoke(aether.clj:411)
    at clojure.lang.RestFn.invoke(RestFn.java:619)
    at leiningen.deploy$deploy.invoke(deploy.clj:187)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.core$apply.invoke(core.clj:626)
    at leiningen.core.main$partial_task$fn__6094.doInvoke(main.clj:263)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:626)
    at leiningen.core.main$apply_task.invoke(main.clj:313)
    at leiningen.core.main$resolve_and_apply.invoke(main.clj:319)
    at leiningen.core.main$_main$fn__6160.invoke(main.clj:392)
    at leiningen.core.main$_main.doInvoke(main.clj:385)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.core$apply.invoke(core.clj:624)
    at clojure.main$main_opt.invoke(main.clj:315)
    at clojure.main$main.doInvoke(main.clj:420)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at clojure.lang.Var.invoke(Var.java:394)
    at clojure.lang.AFn.applyToHelper(AFn.java:165)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact org.clojars.junjiemars:lein-packer:pom:0.1.0 from/to clojars (https://clojars.org/repo/): Access denied to: https://clojars.org/repo/org/clojars/junjiemars/lein-packer/0.1.0/lein-packer-0.1.0.pom, ReasonPhrase: Forbidden.
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:941)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run(WagonRepositoryConnector.java:837)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.put(WagonRepositoryConnector.java:467)
    at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:274)
    ... 39 more
Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Access denied to: https://clojars.org/repo/org/clojars/junjiemars/lein-packer/0.1.0/lein-packer-0.1.0.pom, ReasonPhrase: Forbidden.
    at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:638)
    at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:564)
    at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:546)
    at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:540)
    at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:520)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run(WagonRepositoryConnector.java:811)
    ... 41 more
Failed to deploy artifacts: Could not transfer artifact org.clojars.junjiemars:lein-packer:pom:0.1.0 from/to clojars (https://clojars.org/repo/): Access denied to: https://clojars.org/repo/org/clojars/junjiemars/lein-packer/0.1.0/lein-packer-0.1.0.pom, ReasonPhrase: Forbidden.
```
### My ~/.lein/profiles.cljs

``` clojure
 {:user {:plugins [[cider/cider-nrepl "0.8.1"]]
        :signing {:gpg-key "junjiemars@gmail.com"
        :deploy-repositories [["clojars" {:creds :gpg}]]}
        }}
```
### My ~/.lein/credentials.clj

``` clojure
{#"https://clojars.org/repo" 
            {:username "junjiemars@gmail.com"
             :password "<my-clojars-password>"}}
```

And gpg -d ~/.lein/credentials.clj.gpg is ok. What the problem about lein deploy clojars?

**Comment by hyPiRion** [comment]
Just a quick question here: Is the profiles file named `~/.lein/profiles.cljs`, or did you just misspell `~/.lein/profiles.clj`? (I'd guess the latter, just want to confirm.)

**Comment by junjiemars** [comment]
Hi, hyPiRion,
I'd a typo, it's ~/.lein/credentials.clj

**Comment by hyPiRion** [comment]
That's what I suspected, thanks for verifying. :)

**Comment by strika** [comment]
I have the same problem. It asks for gpg key password 2 times, every time I try `lein deploy clojars` and then it fails with `ReasonPhrase: Forbidden`. This is with Leiningen 2.5.1 on Java 1.8.0_31 Java HotSpot(TM) 64-Bit Server VM.

Let me know I can give more more info. Thanks.

**Comment by stevematdavies** [comment]
I get this issue when tryin gto cider jack in in space macs, but its fine if I run in an external shell. All the work throughs are rather cryptic, I am hoping for a plain english solution soon!

**Comment by glts** [comment]
‘Forbidden’ is the response you get when you use invalid credentials – as you did here: `:username` must be your Clojars username, not your email address.

The GPG prompt appeared twice because there are two artefacts to sign (POM and JAR); use the GPG agent to avoid the second prompt.

With good credentials this works [as advertised](https://github.com/technomancy/leiningen/blob/stable/doc/DEPLOY.md#authentication), I don’t think we can do anything more here.

**Comment by technomancy** [comment]
Yep; this seems to be working right.
