### ISSUE TITLE
Can't use :project/source-paths in aliases

### ISSUE THREAD

**Issue by arrdem** [technomancy/leiningen#1835]
For [lein-grim](https://github.com/clojure-grimoire/lein-grim) I'm attempting to make use of the following alias:

```clojure
:aliases {"grim" ["run" "-m" "grimoire.doc"
                  ,,:project/groupid
                  ,,:project/artifactid
                  ,,:project/version
                  ,,:project/source-paths]}
```

It's not clear to me how, but I'm getting the following exception:

```shell
% lein grim src doc/
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.IFn, compiling:(/tmp/form-init1746183400574885756.clj:1:72)
        at clojure.lang.Compiler.load(Compiler.java:7207)
        at clojure.lang.Compiler.loadFile(Compiler.java:7151)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.IFn
        at user$eval5.invoke(form-init1746183400574885756.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6768)
        at clojure.lang.Compiler.eval(Compiler.java:6758)
        at clojure.lang.Compiler.load(Compiler.java:7195)
        ... 11 more
```

It seems to me that the `:project/source-paths` value stringifies into a `()` list which when string formatted and passed to the child process becomes interpreted as the invocation of the string in the 1st position giving the resulting error. As this is blocking on my lein-grim work I'm gonna put some time into tracking it down but as of my last look at the lein codebase it wasn't clear how to attack solving this. Feedback would be appreciated.

**Comment by hyPiRion** [comment]
[run-form](https://github.com/technomancy/leiningen/blob/a920ddbb7716fdfe4eb62235021153f4caa4f35e/src/leiningen/run.clj#L18-L81) takes the (raw) arguments and doesn't do any sanitizing of them. When they are from the CLI they are always strings, but aliases can pass in non-strings to any task (which happens in this case).

I would guess it would make sense – to provide consistency between aliases and CLI calls – that args passed to run-form are converted to strings by `pr-str`, but only if they're not a string already.

**Comment by arrdem** [comment]
Is there a case when it would be incorrect to simply quote rather than sanitize the inputs? "sanitized" serialization seems to be an open problem in Clojure at the moment and solving that is probably beyond the scope of this PR.

**Comment by arrdem** [comment]
The above patch *should* do it, if I could get lein set up locally for dev thanks to the interference of potemkin as mentioned in IRC.

**Comment by hyPiRion** [comment]
@arrdem It sort of depends on how `lein run` is used, I guess. I've mostly seen it used to call a main function taking CLI args, in which not calling `pr-str` would likely cause a bit of confusion.

I'll have a look at the patch later today, and see if there's a way to support both choices without too much hassle.

**Comment by arrdem** [comment]
Sure, I can imagine `--quote` doing the job just as well.

**Comment by hyPiRion** [comment]
I've added in functionality that stringifies run arguments by default now, and an additional `--quote-args` flag which will quote the arguments instead of stringify them. I'd not recommend relying too heavily on `--quote-args` though, as it's very possible that the functionality will be incompatible with 3.0 changes.

**Comment by arrdem** [comment]
Okay. I'd ask you to keep me posted on how you guys choose to rework this behavior as it's something I _must_ depend heavily on for lein-grim unless I want to go rolling a leiningen plugin to do almost exactly what `--quote-args` will do.

Thanks again!

**Comment by hyPiRion** [comment]
Alright. I know where I can find you, so I'll keep you posted if that happens.
