### ISSUE TITLE
Unable to resolve symbol: *warn-on-reflection* in this context

### ISSUE THREAD

**Issue by klauswuestefeld** [technomancy/leiningen#1868]
Hi,

When I run:
  lein do version, clean, compile

This is the output:
```
Leiningen 2.5.1 on Java 1.7.0_76 Java HotSpot(TM) 64-Bit Server VM
Compiling 2 source files to /c/core/target/classes
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: *warn-on-reflection* in this context, compiling:(/tmp/form-init8903496967135971041.clj:1:77)
	at clojure.lang.Compiler.analyze(Compiler.java:6710)
	at clojure.lang.Compiler.analyze(Compiler.java:6652)
	at clojure.lang.Compiler$AssignExpr$Parser.parse(Compiler.java:707)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6912)
	at clojure.lang.Compiler.analyze(Compiler.java:6691)
	at clojure.lang.Compiler.analyze(Compiler.java:6652)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6028)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5462)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4045)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6898)
	at clojure.lang.Compiler.analyze(Compiler.java:6691)
	at clojure.lang.Compiler.eval(Compiler.java:6968)
	at clojure.lang.Compiler.eval(Compiler.java:6960)
	at clojure.lang.Compiler.load(Compiler.java:7438)
	at clojure.lang.Compiler.loadFile(Compiler.java:7394)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:411)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:728)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: *warn-on-reflection* in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7227)
	at clojure.lang.Compiler.resolve(Compiler.java:7171)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7132)
	at clojure.lang.Compiler.analyze(Compiler.java:6673)
	... 24 more
Compilation failed: Subprocess failed
```

This is my project.clj:

```clojure
(defproject me.sneer/core "0.1.5"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [
                 [org.skummet/clojure "1.7.0-alpha5-r1"]
                 [me.sneer/sneer-java-api "0.1.5"]
                 [me.sneer/crypto "0.1.5"]
                 [org.clojure/core.match "0.2.2"]
                 [org.clojure/core.async "0.1.346.0-17112a-alpha"]
                 [com.cognitect/transit-clj "0.8.259"]
                 [com.netflix.rxjava/rxjava-core "0.20.7"]
                 [com.netflix.rxjava/rxjava-clojure "0.21.0"]
                 [org.clojure/java.jdbc "0.3.6"]
                                        ;[midje "1.6.3"]
                                        ;[org.xerial/sqlite-jdbc "3.8.6"]
                 ]


  :exclusions [[org.clojure/clojure]]

  :omit-source true

  :global-vars {*warn-on-reflection* true}

  :skummet-skip-vars []

  :javac-options ["-target" "1.6" "-source" "1.6" "-Xlint:-options"]

  :aot [
        sneer.restartable
        sneer.party-impl
        sneer.commons
        sneer.tuple.protocols
        sneer.rx-macros
        sneer.rx
        sneer.async
        sneer.tuple-base-provider
        sneer.tuple.persistent-tuple-base
        sneer.tuple.space
        sneer.tuple.queue
        sneer.tuple.tuple-transmitter
        sneer.admin
        sneer.contact
        sneer.conversation
        sneer.impl
        sneer.keys
        sneer.party
        sneer.profile
        sneer.serialization
        sneer.networking.udp
        sneer.networking.client
        sneer.main
        ]
  :uberjar-exclusions [#"META-INF/DUMMY.SF"
                       #"^org/(apache|bouncycastle|json|msgpack|objectweb)"
                       #"^clojure/test/"]

  :jvm-opts ["-Dclojure.compile.ignore-lean-classes=true"]
  :profiles {:default []}
                                        ;  :profiles  {:dev {:plugins [[cider/cider-nrepl "0.8.2"][refactor-nrepl "0.2.2"]]}}
  :plugins [                            ;[lein-midje "3.0.0"]
            [org.skummet/lein-skummet "0.2.1"]]
  :source-paths ["src/main/clojure"]
  :java-source-paths ["src/main/java"]
  :test-paths ["src/test/clojure"])
```

I have also tried compiling with skummet (lein do clean, skummet compile). Same result.

Thanks in advance, Klaus

**Comment by bruskli** [comment]
You can try  :global-vars ^:replace {clojure.core/*warn-on-reflection* true}
or change *warn-on-reflection* to clojure.core/*warn-on-reflection* on definition. It is stated here https://github.com/clojure-android/lein-droid/wiki/Lean-compilation

It doesn't work for me on lein-droid, anyways...

**Comment by hyPiRion** [comment]
As mentioned in previous comment, it seems to be addressed in https://github.com/clojure-android/lein-droid/wiki/Lean-compilation. I'm guessing it's an issue with Skummet rather than Lein (as they've described a fix), so if it's still an issue I would like you to take this up with the Skummet folks. If they believe it's an issue in Leiningen, feel free to reopen this.
