### ISSUE TITLE
Setting -Dline.separator to "\n" causes NullPointerExceptions

### ISSUE THREAD

**Issue by drguildo** [technomancy/leiningen#1891]
When I run `lein repl` in a non-project directory, after a long delay, I get:

```
Exception in thread "Thread-4" java.lang.NullPointerException: key can't be nul

        at java.lang.System.checkKey(System.java:838)
        at java.lang.System.setProperty(System.java:789)
        at leiningen.core.eval$fn__6770.invoke(eval.clj:313)
        at clojure.lang.MultiFn.invoke(MultiFn.java:231)
        at leiningen.core.eval$eval_in_project.invoke(eval.clj:337)
        at leiningen.repl$server$fn__10717.invoke(repl.clj:241)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:624)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invoke(core.clj:628)
        at clojure.core$bound_fn_STAR_$fn__4140.doInvoke(core.clj:1884)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
REPL server launch timed out.
```

**Comment by hyPiRion** [comment]
I'd need some more information about the system you're running on. Does `lein version` fail? If not, could you provide its output?

**Comment by drguildo** [comment]
```
PS C:\Users\Simon> lein version
Leiningen 2.5.1 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM```

**Comment by drguildo** [comment]
I think I've found the cause. I had `:jvm-opts ["-Dline.separator=\"\n\""]` in the user part of my profiles.clj. Removing it seems to have fixed the problem.

I added it to fix the ugly linefeed crap that gets displayed in cider repls.

Any idea what's happening?

**Comment by hyPiRion** [comment]
No, but that certainly helps with debugging it. Thanks for that info.

**Comment by cichli** [comment]
> I added it to fix the ugly linefeed crap that gets displayed in cider repls.

FWIW this is now fixed on master in CIDER - clojure-emacs/cider#1100.

**Comment by glts** [comment]
The NPE is fixed. For reference, this is the correct syntax for setting `line.separator` to a newline:

    :jvm-opts ["-Dline.separator=\n"]
