### ISSUE TITLE
`lein` install script fails with JDK 6

### ISSUE THREAD

**Issue by nrnrnr** [technomancy/leiningen#1894]
When I ran `lein` on my machine, I got the error message below.  Since `lein` is a shell script, it seems reasonable to ask that it detect whether Java is on the machine and is up to date, and if not, that it fail with a message a bit more informative than a stack trace.

Ditto for the situations where it might be necessary to have Clojure installed, but it's not (or is not the right version).

The `lein` I used is the one I downloaded from the web site yesterday.  Its SHA-1 checksum is `b59d741e3ad28b3a11ea28eab417133492ca2138`.

Failure message follows:

````
Exception in thread "main" java.lang.NoClassDefFoundError:
clojure.core.protocols$seq_reduce
   at java.lang.Class.initializeClass(libgcj.so.90)
   at clojure.core.protocols__init.load(Unknown Source:19)
   at clojure.core.protocols__init.<clinit>(Unknown Source)
   at java.lang.Class.initializeClass(libgcj.so.90)
   at java.lang.Class.forName(libgcj.so.90)
   at clojure.lang.RT.loadClassForName(RT.java:2093)
   at clojure.lang.RT.load(RT.java:430)
   at clojure.lang.RT.load(RT.java:411)
   at clojure.core$load$fn__5066.invoke(core.clj:5641)
   at clojure.core$load.doInvoke(core.clj:5640)
   at clojure.lang.RestFn.invoke(RestFn.java:408)
   at clojure.core__init.load(Unknown Source:6270)
   at clojure.core__init.<clinit>(Unknown Source)
   at java.lang.Class.initializeClass(libgcj.so.90)
   at java.lang.Class.forName(libgcj.so.90)
   at clojure.lang.RT.loadClassForName(RT.java:2093)
   at clojure.lang.RT.load(RT.java:430)
   at clojure.lang.RT.load(RT.java:411)
   at clojure.lang.RT.doInit(RT.java:447)
   at clojure.lang.RT.<clinit>(RT.java:329)
   at java.lang.Class.initializeClass(libgcj.so.90)
   at clojure.main.<clinit>(main.java:20)
   at java.lang.Class.initializeClass(libgcj.so.90)
Caused by: java.lang.VerifyError: verification failed at PC 75 in
clojure.core.protocols$seq_reduce:invoke((Ljava.lang.Object;Ljava.lang.Object;L
java.lang.Object;)Ljava.lang.Object;): incompatible type on stack
   at java.lang.Class.initializeClass(libgcj.so.90)
   ...22 more
````

**Comment by shimanekb** [comment]
Leiningen version 2.5.2 is compatible with JDK 6. I was able to successfully self-install, and execute lein commands: test, uberjar, and search on jdk 1.6.0_45.

**Comment by hyPiRion** [comment]
I don't think this is as relevant anymore, as there are fewer and fewer using 1.6 (and we still support relatively updated versions of 1.6, even). If someone is able to reproduce I may reopen, but this doesn't strike me as something that happens for very many people.
