### ISSUE TITLE
NoSuchFileException .../target/base system user dev/classes/...

### ISSUE THREAD

**Issue by holtzermann17** [technomancy/leiningen#1895]
I'm building a Clojure layer over a Java package that uses `java.nio.file.Files.walkFileTree` to identify some of its software components and make them available for interactive use via reflection.  But that wasn't working under Clojure, and the underlying cause took me some time to find.  Once I did it, was easy to come up with a quick fix.

Leiningen compiles the package sources listed in my `defproject`'s `:java-source-paths` slot to `.../project/target/base+system+user+dev`.  But when Java looks for them, for some reason it searches `.../project/target/base system user dev`.

The quick fix was, of course, to add a symlink:

``` bash
.../target$ ln -s base+system+user+dev base\ system\ user\ dev
```

But it seems that there should be a more permanent change in the way Java is instructed to do things.

Here is my full backtrace:

```
java.nio.file.NoSuchFileException: /home/joe/flow/flood/target/base system user dev/classes/ccg/flow/processnodes
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
    at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
    at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
    at java.nio.file.Files.readAttributes(Files.java:1737)
    at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
    at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
    at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
    at java.nio.file.Files.walkFileTree(Files.java:2662)
    at java.nio.file.Files.walkFileTree(Files.java:2742)
    at ccg.flow.model.FlowProcessNodeLister.loadProcessNodesList(FlowProcessNodeLister.java:79)
    at flood.core$eval7559.invoke(form-init2206078685531069079.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6666)
    at clojure.core$eval.invoke(core.clj:2927)
    at clojure.main$repl$read_eval_print__6625$fn__6628.invoke(main.clj:239)
    at clojure.main$repl$read_eval_print__6625.invoke(main.clj:239)
    at clojure.main$repl$fn__6634.invoke(main.clj:257)
    at clojure.main$repl.doInvoke(main.clj:257)
    at clojure.lang.RestFn.invoke(RestFn.java:1523)
    at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__649.invoke(interruptible_eval.clj:72)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invoke(core.clj:624)
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:56)
    at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__691$fn__694.invoke(interruptible_eval.clj:191)
    at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__686.invoke(interruptible_eval.clj:159)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by hyPiRion** [comment]
My first guess here is some code passes in the string `".../project/target/base+system+user+dev"` to a method that expects a URI – in which case the pluses get converted to spaces.

I'm not sure if/how you fetch the `:java-source-paths` or if the java package does that automatically, but could it be that you pass the parameters to a function that expects a URI?

**Comment by glts** [comment]
I don’t think this has anything to do with Leiningen. In the stacktrace we can see that the Java method `FlowProcessNodeLister.loadProcessNodesList` is invoked from Clojure, and that method then tries to access (via `Files.walkFileTree`) the nonexistent file `/home/joe/flow/flood/target/base system user dev/classes/ccg/flow/processnodes`.

To me this looks like a programming error in the Java code, in which case we can close this. Otherwise more info on the repro is appreciated.

**Comment by technomancy** [comment]
Thanks; we can reopen if more details surface.
