### ISSUE TITLE
Leiningen frozen on waiting connection

### ISSUE THREAD

**Issue by SerCeMan** [technomancy/leiningen#1942]
Sometimes, leiningen frozen on waiting of connection.
Restart OS is only solution for me.

Terminal:
```bash
Launching ClojureScript REPL for build: client
Figwheel Controls:
          (stop-autobuild)           ;; stops Figwheel autobuilder
          (start-autobuild [id ...]) ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)   ;; switches autobuilder to different build
          (reset-autobuild)          ;; stops, cleans, and starts autobuilder
          (build-once [id ...])      ;; builds source once time
          (clean-builds [id ..])      ;; deletes compiled cljs target files
          (fig-status)               ;; displays current state of system
          (add-dep [org.om/om "0.8.1"]) ;; add a dependency. very experimental
  Switch REPL build focus:
          :cljs/quit                 ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: Control+C or :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when figwheel connects to your application
```

JStack 
```bash
2015-07-29 15:36:56
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode):

"Attach Listener" #18 daemon prio=9 os_prio=0 tid=0x00007fb4ec001000 nid=0x480c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"ClosingPipeCloser 1990733619" #17 daemon prio=5 os_prio=0 tid=0x00007fb538985000 nid=0x4337 in Object.wait() [0x00007fb50b8fb000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076ed43620> (a java.lang.Thread)
	at java.lang.Thread.join(Thread.java:1245)
	- locked <0x000000076ed43620> (a java.lang.Thread)
	at java.lang.Thread.join(Thread.java:1319)
	at com.hypirion.io.Pipe.join(Pipe.java:120)
	at com.hypirion.io.ClosingPipe$OutCloser.run(ClosingPipe.java:111)
	at java.lang.Thread.run(Thread.java:745)

"PipeThread 1990733619" #16 daemon prio=5 os_prio=0 tid=0x00007fb538983800 nid=0x4336 in Object.wait() [0x00007fb50b9fc000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076eb79720> (a java.lang.Object)
	at java.lang.Object.wait(Object.java:502)
	at com.hypirion.io.RevivableInputStream.read(RevivableInputStream.java:140)
	- locked <0x000000076eb79720> (a java.lang.Object)
	- locked <0x000000076eb79648> (a com.hypirion.io.RevivableInputStream)
	at java.io.InputStream.read(InputStream.java:101)
	at com.hypirion.io.Pipe$PipeOutputStream.run(Pipe.java:239)
	at java.lang.Thread.run(Thread.java:745)

"PipeThread 26357357" #15 daemon prio=5 os_prio=0 tid=0x00007fb538981800 nid=0x4335 runnable [0x00007fb50bafd000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x000000076ed1b288> (a java.lang.UNIXProcess$ProcessPipeInputStream)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x000000076ed397f8> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	- locked <0x000000076ed397f8> (a java.io.InputStreamReader)
	at java.io.Reader.read(Reader.java:140)
	at com.hypirion.io.Pipe$PipeWriter.run(Pipe.java:278)
	at java.lang.Thread.run(Thread.java:745)

"PipeThread 1250603112" #14 daemon prio=5 os_prio=0 tid=0x00007fb538980000 nid=0x4334 runnable [0x00007fb50bbfe000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x000000076ed191c8> (a java.lang.UNIXProcess$ProcessPipeInputStream)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x000000076ed32918> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	- locked <0x000000076ed32918> (a java.io.InputStreamReader)
	at java.io.Reader.read(Reader.java:140)
	at com.hypirion.io.Pipe$PipeWriter.run(Pipe.java:278)
	at java.lang.Thread.run(Thread.java:745)

"process reaper" #12 daemon prio=10 os_prio=0 tid=0x00007fb53897e000 nid=0x4333 runnable [0x00007fb510050000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.UNIXProcess.waitForProcessExit(Native Method)
	at java.lang.UNIXProcess.lambda$initStreams$270(UNIXProcess.java:290)
	at java.lang.UNIXProcess$$Lambda$7/299819831.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"RevivableReader 1607869297" #11 daemon prio=5 os_prio=0 tid=0x00007fb538957000 nid=0x4330 runnable [0x00007fb510151000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:233)
	at com.hypirion.io.RevivableInputStream$ThreadReader.run(RevivableInputStream.java:232)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x00007fb5380d6000 nid=0x432e runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=0 tid=0x00007fb5380c8800 nid=0x432d waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007fb5380c6800 nid=0x432c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007fb5380c4800 nid=0x432b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007fb5380c1800 nid=0x432a waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007fb5380c0000 nid=0x4329 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007fb538088000 nid=0x4328 in Object.wait() [0x00007fb511f5d000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c7415308> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c7415308> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007fb538086000 nid=0x4327 in Object.wait() [0x00007fb51205e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c74154d8> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x00000006c74154d8> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=0 tid=0x00007fb53800a000 nid=0x431d in Object.wait() [0x00007fb54083d000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076ed40fa8> (a java.lang.Thread)
	at java.lang.Thread.join(Thread.java:1245)
	- locked <0x000000076ed40fa8> (a java.lang.Thread)
	at java.lang.Thread.join(Thread.java:1319)
	at com.hypirion.io.Pipe.join(Pipe.java:120)
	at leiningen.core.eval$sh.doInvoke(eval.clj:179)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:624)
	at leiningen.core.eval$fn__6725.invoke(eval.clj:234)
	at clojure.lang.MultiFn.invoke(MultiFn.java:231)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:337)
	at leiningen.figwheel$run_local_project.invoke(figwheel.clj:32)
	at leiningen.figwheel$run_compiler.invoke(figwheel.clj:54)
	at leiningen.figwheel$figwheel.doInvoke(figwheel.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invoke(core.clj:626)
	at leiningen.core.main$partial_task$fn__6094.doInvoke(main.clj:263)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at leiningen.core.main$apply_task.invoke(main.clj:313)
	at leiningen.core.main$resolve_and_apply.invoke(main.clj:319)
	at leiningen.core.main$_main$fn__6160.invoke(main.clj:392)
	at leiningen.core.main$_main.doInvoke(main.clj:385)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.main$main_opt.invoke(main.clj:315)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at clojure.lang.Var.invoke(Var.java:388)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)

"VM Thread" os_prio=0 tid=0x00007fb538080800 nid=0x4326 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007fb53801f800 nid=0x431e runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007fb538021000 nid=0x431f runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007fb538023000 nid=0x4320 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007fb538025000 nid=0x4321 runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00007fb538026800 nid=0x4322 runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00007fb538028800 nid=0x4323 runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00007fb53802a800 nid=0x4324 runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00007fb53802c000 nid=0x4325 runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007fb5380d8800 nid=0x432f waiting on condition 

JNI global references: 323

```

**Comment by SerCeMan** [comment]
Sorry, not appropriate place for issue
