### ISSUE TITLE
Using lein uberjar on master fails

### ISSUE THREAD

**Issue by arichiardi** [technomancy/leiningen#2060]
When compiling master after `lein bootstrap` in `leiningen-core` and `another-lein uberjar` I get an error that I have never had before.

I am living on the edge and wanted to try the new `release` feature :smile:, `another-lein compile` works.

```
kapitan@sea:/usr/local/share/leiningen (master *=)$ ~/bin/lein-stable uberjar
Compiling leiningen.search
WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update
Compiling leiningen.core.utils
Compiling leiningen.core.project
Compiling leiningen.core.classpath
Compiling leiningen.core.main
Compiling leiningen.core.ssl
Compiling leiningen.core.eval
Compiling leiningen.core.user
Compiling leiningen.with-profile
Compiling leiningen.vcs
Compiling leiningen.help
Compiling leiningen.retest
Compiling leiningen.trampoline
Compiling leiningen.classpath
Compiling leiningen.upgrade
Compiling leiningen.uberjar
Compiling leiningen.plugin
Compiling leiningen.show-profiles
Compiling leiningen.search
Compiling leiningen.deploy
Compiling leiningen.deps
Compiling leiningen.version
Compiling leiningen.javac
Compiling leiningen.install
Compiling leiningen.change
Compiling leiningen.compile
Compiling leiningen.jar
Compiling leiningen.test
Compiling leiningen.clean
Compiling leiningen.new
Compiling leiningen.update-in
Compiling leiningen.pom
Compiling leiningen.new.default
Compiling leiningen.new.plugin
Compiling leiningen.new.templates
Compiling leiningen.new.app
Compiling leiningen.new.template
Compiling leiningen.release
nil
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$compile$fn__5453.invoke(core.clj:5877)
	at clojure.core$compile.invoke(core.clj:5876)
	at user$eval11095$fn__11104.invoke(NO_SOURCE_FILE:0)
	at user$eval11095.invoke(NO_SOURCE_FILE:0)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.eval(Compiler.java:6745)
	at clojure.core$eval.invoke(core.clj:3081)
	at leiningen.core.eval$fn__5875.invoke(eval.clj:333)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:356)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:363)
	at leiningen.compile$compile.invoke(compile.clj:147)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invoke(core.clj:632)
	at leiningen.core.main$partial_task$fn__6030.doInvoke(main.clj:261)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at leiningen.core.main$apply_task.invoke(main.clj:311)
	at leiningen.core.eval$run_prep_tasks.invoke(eval.clj:50)
	at leiningen.core.eval$prep.invoke(eval.clj:69)
	at leiningen.jar$build_jar.invoke(jar.clj:288)
	at leiningen.jar$main_jar.invoke(jar.clj:297)
	at leiningen.jar$jar.invoke(jar.clj:348)
	at leiningen.uberjar$uberjar$fn__8107.invoke(uberjar.clj:161)
	at leiningen.uberjar$uberjar.invoke(uberjar.clj:161)
	at leiningen.uberjar$uberjar.invoke(uberjar.clj:180)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invoke(core.clj:632)
	at leiningen.core.main$partial_task$fn__6030.doInvoke(main.clj:261)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at leiningen.core.main$apply_task.invoke(main.clj:311)
	at leiningen.core.main$resolve_and_apply.invoke(main.clj:317)
	at leiningen.core.main$_main$fn__6096.invoke(main.clj:390)
	at leiningen.core.main$_main.doInvoke(main.clj:383)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.main$main_opt.invoke(main.clj:316)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at clojure.lang.Var.invoke(Var.java:388)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.io.IOException: No such file or directory, compiling:(leiningen/release.clj:1:1)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6730)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.eval(Compiler.java:6779)
	at clojure.lang.Compiler.eval(Compiler.java:6771)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at leiningen.release$fn__7912.invoke(release.clj:115)
	at leiningen.release__init.load(Unknown Source)
	at leiningen.release__init.<clinit>(Unknown Source)
	... 71 more
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at clojure.lang.Compiler.writeClassFile(Compiler.java:7263)
	at clojure.lang.Compiler$ObjExpr.compile(Compiler.java:4531)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3983)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
	... 78 more
```

**Comment by hyPiRion** [comment]
This has been happening for quite some time, at least since 2.4.0. You'll have to compile leiningen with itself, as described in the bootstrap section.

In short: run `cd leiningen-core; lein bootstrap; cd ..; bin/lein uberjar` to build Leiningen from source.

**Comment by arichiardi** [comment]
Will try that out and report, I thought I should use a stable version for that last step

**Comment by arichiardi** [comment]
Tried and indeed it works! Sorry for the noise!

**Comment by hyPiRion** [comment]
No worries, it can be easy to miss when building/reading the documentation. =)

I added in a comment in the contributing document to emphasize that you have to use `bin/lein`, so that others may not be caught up by the same issue.

**Comment by arichiardi** [comment]
:+1: and thanks!
