### ISSUE TITLE
colon ":" in project root dir name causes strange compile failures

### ISSUE THREAD

**Issue by gixxi** [technomancy/leiningen#2121]
Hi,

_Context_

I am running the following configuration

```
REPL-y 0.3.7, nREPL 0.2.11
Clojure 1.8.0-RC4
Java HotSpot(TM) 64-Bit Server VM 1.8.0_77-b03
```

on Debian.

AOT config is done by defining a main class in project.cli

```
  ...
  :java-source-paths ["src-java"]
  :source-paths ["src"]
  :test-paths ["test" "test-java"]
  :pre-tasks ["javac" "compile"]
  :main lambdaroyal.vlic.starter
  ...
```

_lambdaroyal.vlic.starter.clj_ is located in _src_ folder.

_Symptom_

When cloning my project from github into an explicit target dir, whose name contains a colon _:_ (I know a bit strange)

> git clone git@github.com:lambdaroyal/rocklog-vlic.git -b 20160328_cloud_deploy rocklog-vlic:20160328_cloud_deploy

then both AOT compile (e.g. lein uberjar) as well as (compile 'lambdaroyal.vlic.starter) fail with the following error

```
Compiling lambdaroyal.vlic.starter
Could not locate lambdaroyal/vlic/starter__init.class or lambdaroyal/vlic/starter.clj on classpath.
Exception in thread "main" java.io.FileNotFoundException: Could not locate lambdaroyal/vlic/starter__init.class or lambdaroyal/vlic/starter.clj on classpath., compiling:(/tmp/form-init5289211476735884903.clj:1:73)
    at clojure.lang.Compiler.load(Compiler.java:7391)
    at clojure.lang.Compiler.loadFile(Compiler.java:7317)
    at clojure.main$load_script.invokeStatic(main.clj:275)
    at clojure.main$init_opt.invokeStatic(main.clj:277)
    at clojure.main$init_opt.invoke(main.clj:277)
    at clojure.main$initialize.invokeStatic(main.clj:308)
    at clojure.main$null_opt.invokeStatic(main.clj:342)
    at clojure.main$null_opt.invoke(main.clj:339)
    at clojure.main$main.invokeStatic(main.clj:421)
    at clojure.main$main.doInvoke(main.clj:384)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate lambdaroyal/vlic/starter__init.class or lambdaroyal/vlic/starter.clj on classpath.
    at clojure.lang.RT.load(RT.java:456)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5671.invoke(core.clj:5892)
    at clojure.core$load.invokeStatic(core.clj:5891)
    at clojure.core$load.doInvoke(core.clj:5875)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invokeStatic(core.clj:5696)
    at clojure.core$compile$fn__5676.invoke(core.clj:5902)
    at clojure.core$compile.invokeStatic(core.clj:5902)
    at clojure.core$compile.invoke(core.clj:5894)
    at user$eval30$fn__39.invoke(form-init5289211476735884903.clj:1)
    at user$eval30.invokeStatic(form-init5289211476735884903.clj:1)
    at user$eval30.invoke(form-init5289211476735884903.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6927)
    at clojure.lang.Compiler.eval(Compiler.java:6917)
    at clojure.lang.Compiler.eval(Compiler.java:6917)
    at clojure.lang.Compiler.load(Compiler.java:7379)
    ... 14 more
Compilation failed: Subprocess failed
```

When I do clone to bread & butter directory _without_ colon, e.g.

> git clone git@github.com:lambdaroyal/rocklog-vlic.git -b 20160328_cloud_deploy rocklog-vlic-edge

then everything works fine.

_Further Information_

checking the classpath in the erroneous variant reveals the following, maybe this helps

```
(doseq [r (seq (.getURLs (java.lang.ClassLoader/getSystemClassLoader)))] (println r))
#object[java.net.URL 0xfe828c0 file:/var/buildbot/rocklog-vlic%5c]
#object[java.net.URL 0x10255cdc file:/var/buildbot/rocklog-vlic:20160328_cloud_deploy/20160328_cloud_deploy/test]
#object[java.net.URL 0x2f8e2ba5 file:/var/buildbot/rocklog-vlic%5c]
#object[java.net.URL 0x23f61e53 file:/var/buildbot/rocklog-vlic:20160328_cloud_deploy/20160328_cloud_deploy/test-java]
#object[java.net.URL 0x6d168cc5 file:/var/buildbot/rocklog-vlic%5c]
#object[java.net.URL 0x57efee07 file:/var/buildbot/rocklog-vlic:20160328_cloud_deploy/20160328_cloud_deploy/src]
#object[java.net.URL 0x962245c file:/var/buildbot/rocklog-vlic%5c]
#object[java.net.URL 0x1a75b7a5 file:/var/buildbot/rocklog-vlic:20160328_cloud_deploy/20160328_cloud_deploy/dev-resources]
#object[java.net.URL 0x435c708a file:/var/buildbot/rocklog-vlic%5c]
#object[java.net.URL 0x6b6b2130 file:/var/buildbot/rocklog-vlic:20160328_cloud_deploy/20160328_cloud_deploy/resources]
#object[java.net.URL 0x73b3a8c5 file:/var/buildbot/rocklog-vlic%5c]
#object[java.net.URL 0x444ce189 file:/var/buildbot/rocklog-vlic:20160328_cloud_deploy/20160328_cloud_deploy/target/classes]
...
```

**Comment by hyPiRion** [comment]
Yeah, this sounds strange. Guessing this has to do with the classpath, as it uses colon for separators.

Not sure how high I would prioritise this one, it's easily avoidable and happens rarely. But it's a bug and I'll be happy to take patches for this.

**Comment by winks** [comment]
Hmm, I'm not 100% sure, but : in file or directory names usually breaks on Windows anyway.
So unless there's some trick I haven't heard of, this will not work on Windows.

**Comment by glts** [comment]
This is simply not possible; avoid colons in directory names.

On Unix systems, the JVM uses `:` as classpath separator. A directory `co:lon` on the classpath is misinterpreted as two directories `co` and `lon`.

On Windows `:` is not allowed in directory names at all.
