### ISSUE TITLE
Upon lein installation I run `lein repl` and got 405 HTTP code when it tries to get the packages from repo

### ISSUE THREAD

**Issue by damianrr** [technomancy/leiningen#2162]
Hi all, 
Upon lein installation I run `lein repl` and got 405 HTTP code when it tries to get the packages from repo.
The traceback is this one:

Could not transfer artifact org.clojure:tools.nrepl:pom:0.2.12 from/to central (https://repo1.maven.org/maven2/): Failed to transfer file: https://repo1.maven.org/maven2/org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.pom. Return code is: 405 , ReasonPhrase:Method Not Allowed.
Could not transfer artifact clojure-complete:clojure-complete:pom:0.2.4 from/to central (https://repo1.maven.org/maven2/): Failed to transfer file: https://repo1.maven.org/maven2/clojure-complete/clojure-complete/0.2.4/clojure-complete-0.2.4.pom. Return code is: 405 , ReasonPhrase:Method Not Allowed.
Could not transfer artifact org.clojure:clojure:pom:1.8.0 from/to central (https://repo1.maven.org/maven2/): Failed to transfer file: https://repo1.maven.org/maven2/org/clojure/clojure/1.8.0/clojure-1.8.0.pom. Return code is: 405 , ReasonPhrase:Method Not Allowed.
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Exception in thread "Thread-3" clojure.lang.ExceptionInfo: Could not resolve dependencies {:suppress-msg true, :exit-code 1}
    at clojure.core$ex_info.invokeStatic(core.clj:4617)
    at clojure.core$ex_info.invoke(core.clj:4617)
    at leiningen.core.classpath$fn__6613.invokeStatic(classpath.clj:295)
    at leiningen.core.classpath$fn__6613.invoke(classpath.clj:253)
    at clojure.lang.AFn.applyToHelper(AFn.java:160)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invokeStatic(core.clj:646)
    at clojure.core$memoize$fn__5708.doInvoke(core.clj:6107)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at leiningen.core.classpath$get_dependencies.invokeStatic(classpath.clj:416)
    at leiningen.core.classpath$get_dependencies.doInvoke(classpath.clj:410)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invokeStatic(core.clj:650)
    at clojure.core$apply.invoke(core.clj:641)
    at leiningen.core.classpath$resolve_dependencies.invokeStatic(classpath.clj:498)
    at leiningen.core.classpath$resolve_dependencies.doInvoke(classpath.clj:489)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at leiningen.core.eval$prep.invokeStatic(eval.clj:84)
    at leiningen.core.eval$prep.invoke(eval.clj:72)
    at leiningen.core.eval$eval_in_project.invokeStatic(eval.clj:369)
    at leiningen.core.eval$eval_in_project.invoke(eval.clj:363)
    at leiningen.repl$server$fn__11767.invoke(repl.clj:243)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invokeStatic(core.clj:646)
    at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invokeStatic(core.clj:650)
    at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Failed to collect dependencies for [#object[org.sonatype.aether.graph.Dependency 0x598fa0f4 "org.clojure:tools.nrepl:jar:0.2.12 (compile)"] #object[org.sonatype.aether.graph.Dependency 0x20756f9c "clojure-complete:clojure-complete:jar:0.2.4 (compile)"] #object[org.sonatype.aether.graph.Dependency 0x6c03c467 "org.clojure:clojure:jar:1.8.0 (compile)"]]
    at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:371)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
    at cemerick.pomegranate.aether$resolve_dependencies_STAR_.invokeStatic(aether.clj:720)
    at cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke(aether.clj:619)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:646)
    at clojure.core$apply.invoke(core.clj:641)
    at cemerick.pomegranate.aether$resolve_dependencies.invokeStatic(aether.clj:729)
    at cemerick.pomegranate.aether$resolve_dependencies.doInvoke(aether.clj:723)
    at clojure.lang.RestFn.invoke(RestFn.java:2088)
    at leiningen.core.classpath$fn__6613.invokeStatic(classpath.clj:258)
    ... 34 more
Caused by: org.sonatype.aether.collection.DependencyCollectionException: Failed to collect dependencies for [#object[org.sonatype.aether.graph.Dependency 0x598fa0f4 "org.clojure:tools.nrepl:jar:0.2.12 (compile)"] #object[org.sonatype.aether.graph.Dependency 0x20756f9c "clojure-complete:clojure-complete:jar:0.2.4 (compile)"] #object[org.sonatype.aether.graph.Dependency 0x6c03c467 "org.clojure:clojure:jar:1.8.0 (compile)"]]
    at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:258)
    at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:333)
    ... 49 more
Caused by: org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.clojure:tools.nrepl:jar:0.2.12
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:296)
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:186)
    at org.sonatype.aether.impl.internal.DefaultDependencyCollector.process(DefaultDependencyCollector.java:412)
    at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:240)
    ... 50 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.clojure:tools.nrepl:pom:0.2.12 from/to central (https://repo1.maven.org/maven2/): Failed to transfer file: https://repo1.maven.org/maven2/org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.pom. Return code is: 405 , ReasonPhrase:Method Not Allowed.
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:281)
    ... 53 more
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact org.clojure:tools.nrepl:pom:0.2.12 from/to central (https://repo1.maven.org/maven2/): Failed to transfer file: https://repo1.maven.org/maven2/org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.pom. Return code is: 405 , ReasonPhrase:Method Not Allowed.
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:941)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
    at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    ... 1 more
Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: https://repo1.maven.org/maven2/org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.pom. Return code is: 405 , ReasonPhrase:Method Not Allowed.
    at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1021)
    at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
    at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
    at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
    at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
    ... 4 more

Any Idea of what might be happening?
Thanks.

**Comment by winks** [comment]
Does [this issue](https://github.com/technomancy/leiningen/issues/2163) help?

**Comment by damianrr** [comment]
Not really, I've just re-install my laptop, I've the latest ubuntu with all packages updated ... and I still have this error

**Comment by technomancy** [comment]
This is probably a problem with the local network you're using; likely some kind of proxy. Unfortunately there's not much Leiningen can do about this.
