### ISSUE TITLE
lein repl fails on internet in China

### ISSUE THREAD

**Issue by jiangts** [technomancy/leiningen#2202]
Trying `lein repl` fails when in China(!!).

Just got off the plane and tried to start a new repl session and got this baffling error message.

```
Exception in thread "main" java.net.ConnectException: Connection refused, compiling:(/private/var/folders/sn/1n8d3s9s6r158gt5rzv0xz080000gp/T/form-init5622892525702900564.clj:1:125)
    at clojure.lang.Compiler.load(Compiler.java:7391)
    at clojure.lang.Compiler.loadFile(Compiler.java:7317)
    at clojure.main$load_script.invokeStatic(main.clj:275)
    at clojure.main$init_opt.invokeStatic(main.clj:277)
    at clojure.main$init_opt.invoke(main.clj:277)
    at clojure.main$initialize.invokeStatic(main.clj:308)
    at clojure.main$null_opt.invokeStatic(main.clj:342)
    at clojure.main$null_opt.invoke(main.clj:339)
    at clojure.main$main.invokeStatic(main.clj:421)
    at clojure.main$main.doInvoke(main.clj:384)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at java.net.Socket.connect(Socket.java:538)
    at java.net.Socket.<init>(Socket.java:434)
    at java.net.Socket.<init>(Socket.java:211)
    at clojure.tools.nrepl$connect.invokeStatic(nrepl.clj:184)
    at clojure.tools.nrepl$connect.doInvoke(nrepl.clj:174)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.tools.nrepl.ack$send_ack.invokeStatic(ack.clj:47)
    at clojure.tools.nrepl.ack$send_ack.invoke(ack.clj:45)
    at clojure.tools.nrepl.server$start_server.invokeStatic(server.clj:157)
    at clojure.tools.nrepl.server$start_server.doInvoke(server.clj:121)
    at clojure.lang.RestFn.invoke(RestFn.java:619)
    at user$eval17285.invokeStatic(form-init5622892525702900564.clj:1)
    at user$eval17285.invoke(form-init5622892525702900564.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6927)
    at clojure.lang.Compiler.eval(Compiler.java:6917)
    at clojure.lang.Compiler.eval(Compiler.java:6917)
    at clojure.lang.Compiler.load(Compiler.java:7379)
    ... 14 more
```

Tried everything I could think of, and finally tried turning off the internet and trying it again, and voila, it worked! First, wondering what `lein repl` is trying to request on the network, and second, a graceful failure/helpful error message would save others lots of time

**Comment by hyPiRion** [comment]
It's hard to know the exact cause of this unfortunately, but I agree that the error message is ugly. I'm happy to take patches to improve this.

**Comment by linpengcheng** [comment]
I hope Lein support breakpoint Continuation

**Comment by geokon-gh** [comment]
The reason as far as I've pieced together is that github assets/archives/gists are hosted on Amazon's cloud. This is also being used by a lot of VPN services b/c of the anonymizing they provide - so this ends up semi-randomly getting slammed by the firewall b/c something gets tripped. So I on occasion I will no longer be able to download github archives from home for a few hours (and gists seem to basically never work). But if I go downstairs to a cafe it will work - so there is some IP-based filtering going on.

A work around would be to maybe do get lein through a git-clone (if possible) - maybe as a backup option?

**Comment by winks** [comment]
This is very unfortunate, but it seems GitHub uses Amazon behind the scenes to host the release artifacts.
I might be remembering this incorrectly but I recall @technomancy saying we don't want to host on 2 different URLs, e.g. on leiningen.org. So unless we'd get a second (semi-)official mirror I don't see a way out here.

**Comment by geokon-gh** [comment]
This is not a big issue for the time being. Just intermittent connectivity issues. I'd revisit this if Amazon gets actually permanently blocks

**Comment by technomancy** [comment]
This doesn't have anything to do with China's firewall; it's being blocked by the OS-level firewall between the nrepl server and the client. If the OS is configured to block this connection there's not really anything we can do about it.
