### ISSUE TITLE
Can't start lein due to java.security.NoSuchAlgorithmException

### ISSUE THREAD

**Issue by ILoveHubGit** [technomancy/leiningen#2203]
I'm new to Lein so I probably did not install it correct, but I can't find what is wrong.

I followed the instructions to install Lein from Leiningen.org
But when I try to start Lein repl I get the following error message:
Sep 10, 2016 11:55:48 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo1.maven.org:443: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)

If I try wget https://repo1.maven.org/ I get this error:
--2016-09-10 12:23:24--  https://repo1.maven.org/
Resolving repo1.maven.org (repo1.maven.org)... 151.101.36.209
Connecting to repo1.maven.org (repo1.maven.org)|151.101.36.209|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-09-10 12:23:24 ERROR 403: Forbidden.

Running the above commands as sudo does not change the error message

If I use my browser to connect to https://repo1.maven.org/ I have no problem to view this site an navigate through all the folders

Can anyone help me to solve this security problem?

**Comment by hyPiRion** [comment]
On what system do you run on?

Typically this happens when there is something fishy going on with the java keystore. It usually seems to help to do `sudo update-ca-certificates -f`. If `update-ca-certificates` is not available, install it via `sudo apt-get install ca-certificates`.

**Comment by ILoveHubGit** [comment]
I'm running this on Ubuntu 16.04 LTS

I was able to run sudo update-ca-certificates. However this gives me an error on the Java keystore

Running hooks in /etc/ca-certificates/update.d...

org.debian.security.InvalidKeystorePasswordException: Cannot open Java keystore. Is the password correct?
	at org.debian.security.KeyStoreHandler.load(KeyStoreHandler.java:68)
	at org.debian.security.KeyStoreHandler.<init>(KeyStoreHandler.java:52)
	at org.debian.security.UpdateCertificates.<init>(UpdateCertificates.java:65)
	at org.debian.security.UpdateCertificates.main(UpdateCertificates.java:51)
Caused by: java.io.IOException: Invalid keystore format
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:658)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at org.debian.security.KeyStoreHandler.load(KeyStoreHandler.java:66)
	... 3 more
E: /etc/ca-certificates/update.d/jks-keystore exited with code 1.

**Comment by hyPiRion** [comment]
Hm, see if `sudo apt-get install ca-certificates-java` works. If that doesn't work, try out

```
sudo dpkg --purge --force-depends ca-certificates-java
sudo apt-get install ca-certificates-java
```

**Comment by ILoveHubGit** [comment]
Hi hyPiRion,

I followed your instructions. After the first command I got a message to restart to finish installing the updates so I restarted my PC.
However, after the restart still the same problem.

So I executed the other two commands and now it is working :-)

Thanks a lot

**Comment by wallydrag** [comment]
I am having the same issue but on a macbook. Can anyone recommend me any solution?

**Comment by hyPiRion** [comment]
@wallydrag: How did you install Leiningen? Was it via brew or did you just download the script and put it on your path?

In either case, this may happen if there are some issues with the Java certificates. Usually some way of recreating them or fixing them will resolve this issue.

**Comment by wallydrag** [comment]
I think i downloaded the script. Anyway leiningen is working for me. 

What I did was I downloaded the latest oracle jdk and created another keystore with respect to the new jdk. 

`keytool -list -keystore $(/usr/libexec/java_home)/jre/lib/security/cacerts`

^ this worked for me but

`keytool -list` did not.

I noticed that my JAVA_HOME env variable was not updated, so I updated and again did a `keytool -list` , but sigh it failed again. But my lein started working.

**Comment by venkateshseerapu** [comment]
Hi @hypirion 

Do you have any solution to solve the below issue with sending email through Jenkins.

`javax.mail.MessagingException: Could not connect to SMTP host: hostname, port: 465;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1934)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)
	at javax.mail.Service.connect(Service.java:317)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at hudson.tasks.MailSender.run(MailSender.java:131)
	at hudson.tasks.Mailer.perform(Mailer.java:173)
	at hudson.tasks.Mailer.perform(Mailer.java:136)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1843)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:507)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)
	... 18 more`

**Comment by danielcompton** [comment]
@venkateshseerapu your issue is not related to Leiningen, so we can't help you here. It looks like a certificate issue, but a Jenkins forum may able to be more helpful.
