### ISSUE TITLE
Lein trampoline is exception  in Clojure 1.9.0-alpha16 or  alpha17.

### ISSUE THREAD

**Issue by linpengcheng** [technomancy/leiningen#2296]
Lein trampoline is ok  in Clojure 1.9.0-alpha14 or  alpha15, 
Lein trampoline   is exception  in Clojure 1.9.0-alpha16 or  alpha17 , 
alpha16 or  alpha17 is spec-separated version,
should be the spec separation caused by the bug?

Exception in thread "main" java.io.FileNotFoundException: E:\temp\form-init820515111953380484.clj (The system cannot find the specified file.)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at clojure.lang.Compiler.loadFile(Compiler.java:7392)
        at clojure.main$load_script.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invokeStatic(main.clj:279)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invokeStatic(main.clj:310)
        at clojure.main$null_opt.invokeStatic(main.clj:344)
        at clojure.main$null_opt.invoke(main.clj:341)
        at clojure.main$main.invokeStatic(main.clj:423)
        at clojure.main$main.doInvoke(main.clj:386)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)

**Comment by glts** [comment]
I have used `lein trampoline` with 1.9.0-alpha17 a lot the past few weeks, and have never had any trouble. Can you provide steps to reproduce?

**Comment by technomancy** [comment]
Closing this, but I can reopen if a repro case is found.

**Comment by linpengcheng** [comment]
it ok after add  
[org.clojure/spec.alpha "0.1.123"] 
[org.clojure/core.specs.alpha "0.1.24"]
to project.clj
