### ISSUE TITLE
Unhelpful stack trace from `lein test`

### ISSUE THREAD

**Issue by rnikander** [technomancy/leiningen#2314]
I ran `lein test` and got this.

Seems like it's complaining about a bad import, but the stack trace and message gives me absolutely zero info about where the error is. Am I missing something, or should this be fixed?  Or it a Clojure issue?

    rob$ lein test
    Compiling 27 source files to /Users/rob/Workspace/MyApp/target/base+system+user+dev+test+test/classes
    Compiling 27 source files to /Users/rob/Workspace/MyApp/target/base+system+user+dev+test+test/classes
    Exception in thread "main" java.io.FileNotFoundException: Could not locate co/encodia/app__init.class or co/encodia/app.clj on classpath., compiling:(/private/var/folders/89/m2gt8s0x4gsfpdvy7x7dxwm40000gn/T/form-init3070645524310374000.clj:1:125)
    	at clojure.lang.Compiler.load(Compiler.java:7391)
    	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
    	at clojure.main$load_script.invokeStatic(main.clj:275)
    	at clojure.main$init_opt.invokeStatic(main.clj:277)
    	at clojure.main$init_opt.invoke(main.clj:277)
    	at clojure.main$initialize.invokeStatic(main.clj:308)
    	at clojure.main$null_opt.invokeStatic(main.clj:342)
    	at clojure.main$null_opt.invoke(main.clj:339)
    	at clojure.main$main.invokeStatic(main.clj:421)
    	at clojure.main$main.doInvoke(main.clj:384)
    	at clojure.lang.RestFn.invoke(RestFn.java:421)
    	at clojure.lang.Var.invoke(Var.java:383)
    	at clojure.lang.AFn.applyToHelper(AFn.java:156)
    	at clojure.lang.Var.applyTo(Var.java:700)
    	at clojure.main.main(main.java:37)
    Caused by: java.io.FileNotFoundException: Could not locate co/encodia/app__init.class or co/encodia/app.clj on classpath.
    	at clojure.lang.RT.load(RT.java:456)
    	at clojure.lang.RT.load(RT.java:419)
    	at clojure.core$load$fn__5677.invoke(core.clj:5893)
    	at clojure.core$load.invokeStatic(core.clj:5892)
    	at clojure.core$load.doInvoke(core.clj:5876)
    	at clojure.lang.RestFn.invoke(RestFn.java:408)
    	at clojure.core$load_one.invokeStatic(core.clj:5697)
    	at clojure.core$load_one.invoke(core.clj:5692)
    	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
    	at clojure.core$load_lib.invokeStatic(core.clj:5736)
    	at clojure.core$load_lib.doInvoke(core.clj:5717)
    	at clojure.lang.RestFn.applyTo(RestFn.java:142)
    	at clojure.core$apply.invokeStatic(core.clj:648)
    	at clojure.core$load_libs.invokeStatic(core.clj:5774)
    	at clojure.core$load_libs.doInvoke(core.clj:5758)
    	at clojure.lang.RestFn.applyTo(RestFn.java:137)
    	at clojure.core$apply.invokeStatic(core.clj:648)
    	at clojure.core$require.invokeStatic(core.clj:5796)
    	at clojure.core$require.doInvoke(core.clj:5796)
    	at clojure.lang.RestFn.applyTo(RestFn.java:137)
    	at clojure.core$apply.invokeStatic(core.clj:648)
    	at clojure.core$apply.invoke(core.clj:641)
    	at user$eval85.invokeStatic(form-init3070645524310374000.clj:1)
    	at user$eval85.invoke(form-init3070645524310374000.clj:1)
    	at clojure.lang.Compiler.eval(Compiler.java:6927)
    	at clojure.lang.Compiler.eval(Compiler.java:6917)
    	at clojure.lang.Compiler.load(Compiler.java:7379)
    	... 14 more
    Tests failed.

**Comment by technomancy** [comment]
> Seems like it's complaining about a bad import, but the stack trace and message gives me absolutely zero info about where the error is. Am I missing something, or should this be fixed? Or it a Clojure issue?

Do you mean that this is inaccurate?

> Caused by: java.io.FileNotFoundException: Could not locate co/encodia/app__init.class or co/encodia/app.clj on classpath.

If so I would need more details about the project to see what the real
problem is and why this error message was shown instead.

**Comment by rnikander** [comment]
Sorry, I shouldn't have written "absolutely zero info". I guess the error is accurate, though I'm new to Clojure and wasn't sure what it meant at first. I was able to find and fix it by searching the code for that symbol. But, I usually expect compilation errors to come with source locations (file, line number). Is that not expected here?

**Comment by technomancy** [comment]
> But, I usually expect compilation errors to come with source locations (file, line number). Is that not expected here?

Without knowing more about the problem it's hard to say.

**Comment by rnikander** [comment]
I've attached a minimal example in a zip file. Try running `lein test`. 

[hello-world.zip](https://github.com/technomancy/leiningen/files/1309422/hello-world.zip)

**Comment by technomancy** [comment]
Yeah; this is a problem with Clojure giving a bad error message when Leiningen tries to load your source file.
