### ISSUE TITLE
Lein Uberjar Later Results in ExceptionInInitializerError When Running

### ISSUE THREAD

**Issue by clov0** [technomancy/leiningen#2316]
On `[org.clojure/clojure "1.8.0"]` and using `:uberjar {:aot :all}`
I'm using the `clojure:onbuild` docker image it runs on openjdk 8 using the `openjdk:8-alpine` image and leiningen 2.7.1

Running the jar file causes  :

```java
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(java.base@9-internal/Native Method)
	at java.lang.Class.forName(java.base@9-internal/Class.java:378)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at uncomplicate.fluokitten.core$loading__5569__auto____3776.invoke(core.clj:9)
	at uncomplicate.fluokitten.core__init.load(Unknown Source)
	at uncomplicate.fluokitten.core__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(java.base@9-internal/Native Method)
	at java.lang.Class.forName(java.base@9-internal/Class.java:378)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:2088)
	at stellar.access.samples.consumer$loading__5569__auto____2873.invoke(consumer.clj:1)
	at stellar.access.samples.consumer__init.load(Unknown Source)
	at stellar.access.samples.consumer__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(java.base@9-internal/Native Method)
	at java.lang.Class.forName(java.base@9-internal/Class.java:378)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.Util.loadWithClass(Util.java:250)
	at stellar.access.samples.consumer.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: clojure.core.reducers.CollFold
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@9-internal/BuiltinClassLoader.java:366)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@9-internal/ClassLoaders.java:184)
	at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:419)
	at java.lang.Class.forName0(java.base@9-internal/Native Method)
	at java.lang.Class.forName(java.base@9-internal/Class.java:378)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at uncomplicate.fluokitten.algo__init.__init2(Unknown Source)
	at uncomplicate.fluokitten.algo__init.<clinit>(Unknown Source)
	... 70 more
```

project.clj : 

```clojure
  :main nil
  :target-path "target/%s"

  :jvm-opts ["-Xmx2g" "-Xms512m" "-XX:+UseConcMarkSweepGC"]
  :profiles {:uberjar {:aot :all}
             :dev     {:dependencies [[midje "1.8.3"]
                                      [jonase/eastwood "0.2.4" :exclusions [org.clojure/clojure]]]}})
```

**Comment by clov0** [comment]
Specifying the `clojure.core.reducers` fixes the issue. 
Just posted to make sure it is not indicative of a more serious bug.

**Comment by technomancy** [comment]
I can't reproduce this problem with the `project.clj` data provided above; can you provide a repro case with more details?

**Comment by clov0** [comment]
Here is a sample project that produces this exception :
https://github.com/clov0/fluotest

**Comment by technomancy** [comment]
Can't reproduce, and the sample project is gone. Please feel free to reopen if there's a repro case.
