### ISSUE TITLE
Leiningen sometimes fails to build on 32-bit architectures

### ISSUE THREAD

**Issue by ehashman** [technomancy/leiningen#2458]
While i386 is maybe going the way of the dinosaur, armhf is a very popular 32-bit architecture that this affects (hello, raspis).

Building Leiningen on armhf on Debian sometimes yields the following stacktrace:

```

Compiling clojure.tools.nrepl
java.lang.ClassCastException: clojure.lang.PersistentVector cannot be cast to java.base/java.lang.CharSequence
	at clojure.string$split.invokeStatic(string.clj:219)
	at clojure.string$split.invoke(string.clj:219)
	at clojure.data.xml$qualified_name.invokeStatic(xml.clj:30)
	at clojure.data.xml$qualified_name.invoke(xml.clj:27)
	at clojure.data.xml$emit_start_tag.invokeStatic(xml.clj:48)
	at clojure.data.xml$emit_start_tag.invoke(xml.clj:47)
	at clojure.data.xml$emit_event.invokeStatic(xml.clj:67)
	at clojure.data.xml$emit_event.invoke(xml.clj:65)
	at clojure.data.xml$emit.invokeStatic(xml.clj:379)
	at clojure.data.xml$emit.doInvoke(xml.clj:366)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$apply.invoke(core.clj:641)
	at clojure.data.xml$indent.invokeStatic(xml.clj:402)
	at clojure.data.xml$indent.doInvoke(xml.clj:396)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.data.xml$indent_str.invokeStatic(xml.clj:411)
	at clojure.data.xml$indent_str.invoke(xml.clj:407)
	at leiningen.pom$make_pom.invokeStatic(pom.clj:390)
	at leiningen.pom$make_pom.invoke(pom.clj:381)
	at leiningen.pom$make_pom.invokeStatic(pom.clj:382)
	at leiningen.pom$make_pom.invoke(pom.clj:381)
	at leiningen.jar$filespecs.invokeStatic(jar.clj:200)
	at leiningen.jar$filespecs.invoke(jar.clj:191)
	at leiningen.jar$build_jar.invokeStatic(jar.clj:284)
	at leiningen.jar$build_jar.invoke(jar.clj:280)
	at leiningen.jar$main_jar.invokeStatic(jar.clj:292)
	at leiningen.jar$main_jar.invoke(jar.clj:288)
	at leiningen.jar$jar.invokeStatic(jar.clj:343)
	at leiningen.jar$jar.invoke(jar.clj:325)
	at leiningen.uberjar$uberjar$fn__7843.invoke(uberjar.clj:167)
	at leiningen.uberjar$uberjar.invokeStatic(uberjar.clj:167)
	at leiningen.uberjar$uberjar.invoke(uberjar.clj:143)
	at leiningen.uberjar$uberjar.invokeStatic(uberjar.clj:187)
	at leiningen.uberjar$uberjar.invoke(uberjar.clj:143)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.main$partial_task$fn__6272.doInvoke(main.clj:284)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.main$apply_task.invokeStatic(main.clj:334)
	at leiningen.core.main$apply_task.invoke(main.clj:320)
	at leiningen.core.main$resolve_and_apply.invokeStatic(main.clj:340)
	at leiningen.core.main$resolve_and_apply.invoke(main.clj:336)
	at leiningen.core.main$_main$fn__6339.invoke(main.clj:420)
	at leiningen.core.main$_main.invokeStatic(main.clj:411)
	at leiningen.core.main$_main.doInvoke(main.clj:408)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at clojure.main$main_opt.invokeStatic(main.clj:316)
	at clojure.main$main_opt.invoke(main.clj:310)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at clojure.lang.Var.invoke(Var.java:388)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Uberjar aborting because jar failed: clojure.lang.PersistentVector cannot be cast to java.base/java.lang.CharSequence
```

This sounds to me like it might be an issue with the old org.clojure/data.xml decoder.

I keep meaning to try to reproduce this with an upstream Leiningen build (rather than the Debian build) but finding a 32-bit machine is not the simplest task. I do have some build machines from Debian I can try this on if I stop forgetting.

**Comment by ehashman** [comment]
Someone is encountering this occasionally on 64-bit architectures as well: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908085

I wonder if upgrading data.xml would help here at all. The stacktrace suggests that the root of the issue might be there.

**Comment by glts** [comment]
I’m afraid (or happy?) it may not be possible to reproduce this any more on Leiningen master.

We did the upgrade of data.xml from 0.0.8 → 0.2.0-alpha5, and now not a line of the old code remains. Though I would have been curious to know what causes this exception …

**Comment by ehashman** [comment]
If it's not reproducible after the upgrade I'd call the bug fixed. I'm going to hold off on declaring that until Debian buster gets released though, as it's easiest to test this on the armhf/i386 CI infra I get for free there and I'm not going to do a new upload of Leiningen until after release. We will need the data.xml upgrade to hit a release version first.

**Comment by glts** [comment]
If I’m reading it proper, @ehashman requested to keep this open?

**Comment by technomancy** [comment]
Oops; yeah I misread.

**Comment by technomancy** [comment]
Haven't heard anything more about this but I can reopen if it still occurs.
