### ISSUE TITLE
ERROR: Unhandled REPL handler exception processing message

### ISSUE THREAD

**Issue by CptHaddock** [technomancy/leiningen#2545]
Hi there. This is an out-of-the-box issue. (Linux)
lein -v
Leiningen 2.9.1 on Java 11.0.2 OpenJDK 64-Bit Server VM
(NOTE: Same prop w/ OpenJDK 8)
mkdir test-projects
cd test-projects
lein new figwheel my-new-test-proj -- --reagent
cd my-new-test-proj
lein figwheel (WORKS!)
BUT...
lein repl
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
nREPL server started on port 44855 on host 127.0.0.1 - nrepl://127.0.0.1:44855
ERROR: Unhandled REPL handler exception processing message {:id 18cbb7aa-62d2-42f3-93dc-2d3d8245418e, :op clone}
java.lang.NullPointerException
	at clojure.core$deref_future.invokeStatic(core.clj:2300)
	at clojure.core$deref.invokeStatic(core.clj:2320)
	at clojure.core$deref.invoke(core.clj:2306)
	at cider.piggieback$wrap_cljs_repl$fn__22756.invoke(piggieback.clj:222)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__17875.invoke(middleware.clj:22)
	at nrepl.server$handle_STAR_.invokeStatic(server.clj:18)
	at nrepl.server$handle_STAR_.invoke(server.clj:15)
	at nrepl.server$handle$fn__22378.invoke(server.clj:27)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

As I said, this is an out-of-the-box problem with a blank clojurescript / figwheel project on GNU/Linux (4.19.28).

Smells like a current leiningen mis-configuration / bug. But if it's me, where am I going wrong? 
Any help is really appreciated. Cheers.

EDIT: clojure
Clojure 1.10.0

**Comment by CptHaddock** [comment]
Found it. It's piggieback.

Update to version 0.4.0:
:profiles {:dev {:dependencies [[binaryage/devtools "0.9.9"]
                                  [figwheel-sidecar "0.5.16"]
                                  [cider/piggieback "0.4.0"]

Initially leiningen creates a project.clj with:
                                  [cider/piggieback "0.3.1"]
