### ISSUE TITLE
Exception after upgrading to Java 13

### ISSUE THREAD

**Issue by starnold101** [technomancy/leiningen#2623]
After upgrading my Java to the latest version and Leiningen returns this error message: Exception in thread "main" java.lang.UnsupportedClassVersionError: clojure/main : Unsupported major.minor version 52.0.

I cycled through downdgrades and upgrades (java 6, 7, 8 and the latest) reinstalled Leiningen, but each time I try to run Lein I still get the same error message. I tried googling for solutions, but it's mostly just upgrading Java to the latest version.

Any help would be very much appreciated.

Here's the complete error message:

Exception in thread "main" java.lang.UnsupportedClassVersionError: clojure/main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by technomancy** [comment]
It sounds like you probably have multiple versions of Java installed at once.

How did you install Java, and how did you install Leiningen? We strongly
recommend using OpenJDK 8 at this time.

**Comment by starnold101** [comment]
Thank heaps for the reply! I downgraded my Java, installed Leiningen then updated Java. Works okay now. 

Regards,

Arnold Patolot
e: arnoldpatolot@gmail.com
t: 0457 291 563
 

    On Tuesday, 8 October 2019, 11:38:33 am AEDT, Phil Hagelberg <notifications@github.com> wrote:  
 
 It sounds like you probably have multiple versions of Java installed at once.

How did you install Java, and how did you install Leiningen? We strongly
recommend using OpenJDK 8 at this time.
