### ISSUE TITLE
Need suggestions for Sonarqube analysis for Clojure projects using Leiningen Build tool

### ISSUE THREAD

**Issue by balajisivaramgari** [technomancy/leiningen#2635]
Hi Team, 
We have a Clojure project and we would like to integrate the Clojure project with Sonarqube for code analysis. The build tool we are trying to use is Leiningen though Jenkins. 
Would you please provide us the guidelines?

Thanks in Advance
Balaji

**Comment by winks** [comment]
I've never heard anyone mention sonarqube 'round here it's been like 8 years since I used it (not for Clojure).
A quick google search yielded https://github.com/zmsp/sonar-clojure - maybe try that one? Sounds reasonable, I did integrate kibit in a project at some point so that seems feasible.

**Comment by balajisivaramgari** [comment]
Yes, I tried that. And also followed https://github.com/fsantiag/sonar-clojure article as well. It was working for Maven and Gradle. But we are trying Leiningen with Sonarqube. 


Here is the error we are getting 

root@test-sonarqube:/opt/git/sonar-clojure# lein lein-cloverage
'lein-cloverage' is not a task. See 'lein help'.

**Comment by balajisivaramgari** [comment]
root@test-sonarqube:/opt/git/sonar-clojure# lein cloverage
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: update in this context, compiling:(cloverage/args.clj:81:20)
        at clojure.lang.Compiler.analyze(Compiler.java:6464)
        at clojure.lang.Compiler.analyze(Compiler.java:6406)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3665)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.analyze(Compiler.java:6406)
        at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2708)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.analyze(Compiler.java:6406)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
        at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6100)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.analyze(Compiler.java:6406)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.analyze(Compiler.java:6406)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.analyze(Compiler.java:6406)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.access$100(Compiler.java:38)
        at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:538)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.analyze(Compiler.java:6406)
        at clojure.lang.Compiler.eval(Compiler.java:6707)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.loadResourceScript(RT.java:361)
        at clojure.lang.RT.load(RT.java:440)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:3204)
        at cloverage.coverage$eval9$loading__4958__auto____10.invoke(coverage.clj:1)
        at cloverage.coverage$eval9.invoke(coverage.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6692)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.loadResourceScript(RT.java:361)
        at clojure.lang.RT.load(RT.java:440)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at user$eval5.invoke(form-init3959019222139102575.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6692)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: update in this context
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.Compiler.resolveIn(Compiler.java:6940)
        at clojure.lang.Compiler.resolve(Compiler.java:6884)
        at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6845)
        at clojure.lang.Compiler.analyze(Compiler.java:6427)
        ... 98 more

**Comment by balajisivaramgari** [comment]
Clojure version:

root@test-sonarqube:/opt/git/sonar-clojure# lein -v
Leiningen 2.8.1 on Java 1.8.0_222 OpenJDK 64-Bit Server VM

**Comment by balajisivaramgari** [comment]
The above error is because of the version mis-match ([lein-cloverage "1.0.10"]) after downgrading the lein-cloverage version to 1.0.10, the issue is resolve. But we are getting different error. 

root@test-sonarqube:/opt/git/sonar-clojure# lein cloverage
Exception in thread "main" java.lang.ClassNotFoundException: clojure.tools.namespace, compiling:(/tmp/form-init8748932387340334319.clj:1:122)
        at clojure.lang.Compiler.analyze(Compiler.java:6464)
        at clojure.lang.Compiler.analyze(Compiler.java:6406)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3665)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.analyze(Compiler.java:6406)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.analyze(Compiler.java:6406)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)
        at clojure.lang.Compiler.analyze(Compiler.java:6445)
        at clojure.lang.Compiler.eval(Compiler.java:6700)
        at clojure.lang.Compiler.eval(Compiler.java:6692)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: clojure.tools.namespace
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2065)
        at clojure.lang.Compiler.resolveIn(Compiler.java:6921)
        at clojure.lang.Compiler.resolve(Compiler.java:6884)
        at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6845)
        at clojure.lang.Compiler.analyze(Compiler.java:6427)
        ... 28 more


Thanks in advance
Balaji

**Comment by balajisivaramgari** [comment]
~/.lein/profiles.clj file

root@test-sonarqube:/opt/git/sonar-clojure# cat ~/.lein/profiles.clj
{:user {:dependencies [[org.clojure/tools.namespace "0.2.3"]]
        :injections [(require (clojure.tools.namespace repl find))
                     (try (require spyscope.core)
                       (catch RuntimeException e))]
        :plugins [[lein-pprint "1.1.1"]
                  [lein-beanstalk "0.2.6"]
                  [lein-clojars "0.9.1"]
                  [lein-create-template "0.1.1"]
                  [lein-marginalia "0.7.1"]
                  [lein-exec "0.3.1"]
                  [lein-midje "3.1.1"]
                  [jonase/eastwood "0.3.5"]
                  [lein-kibit "0.0.8"]
                  [lein-cloverage "1.0.10"]]}}

**Comment by balajisivaramgari** [comment]
Hi Team, 
I was able to generate the sonarqube report from the Leiningen. But we are getting the below error after the report. 

17:41:46  recompiling all files in /home/jenkins/workspace/SonarqubeClojureTest/test/src/java
17:41:46  :reloading (datastream.test.core datastream.test.integration datastream.test.profile datastream.test.main datastream.test.lint)
17:41:48  :error-while-loading datastream.test.core
17:41:49  Loading namespaces:  (datastream.test.integration datastream.test.lint datastream.test.profile datastream.test.main datastream.test.core)
17:41:49  Test namespaces:  (datastream.test.integration datastream.test.lint datastream.test.profile)
17:41:49  Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class conflux.impl.memka.core__init, compiling:(/tmp/form-init4025771764530416015.clj:1:73)
17:41:49       at clojure.lang.Compiler.load(Compiler.java:7526)
17:41:49   at clojure.lang.Compiler.loadFile(Compiler.java:7452)
17:41:49   at clojure.main$load_script.invokeStatic(main.clj:278)
17:41:49          at clojure.main$init_opt.invokeStatic(main.clj:280)
17:41:49    at clojure.main$init_opt.invoke(main.clj:280)
17:41:49    at clojure.main$initialize.invokeStatic(main.clj:311)
17:41:49    at clojure.main$null_opt.invokeStatic(main.clj:345)
17:41:49      at clojure.main$null_opt.invoke(main.clj:342)
17:41:49      at clojure.main$main.invokeStatic(main.clj:424)
17:41:49    at clojure.main$main.doInvoke(main.clj:387)
17:41:49      at clojure.lang.RestFn.applyTo(RestFn.java:137)
17:41:49    at clojure.lang.Var.applyTo(Var.java:702)
17:41:49        at clojure.main.main(main.java:37)
17:41:49  Caused by: java.lang.NoClassDefFoundError: Could not initialize class conflux.impl.memka.core__init
17:41:49        at java.lang.Class.forName0(Native Method)
17:41:49     at java.lang.Class.forName(Class.java:348)
17:41:49        at clojure.lang.RT.classForName(RT.java:2204)
17:41:49        at clojure.lang.RT.classForName(RT.java:2213)
17:41:49        at clojure.lang.RT.loadClassForName(RT.java:2232)
17:41:49    at clojure.lang.RT.load(RT.java:450)
17:41:49     at clojure.lang.RT.load(RT.java:426)
17:41:49      at clojure.core$load$fn__6548.invoke(core.clj:6046)
17:41:49        at clojure.core$load.invokeStatic(core.clj:6045)
17:41:49     at clojure.core$load.doInvoke(core.clj:6029)
17:41:49      at clojure.lang.RestFn.invoke(RestFn.java:408)
17:41:49     at clojure.core$load_one.invokeStatic(core.clj:5848)
17:41:49      at clojure.core$load_one.invoke(core.clj:5843)
17:41:49     at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
17:41:49   at clojure.core$load_lib.invokeStatic(core.clj:5887)
17:41:49    at clojure.core$load_lib.doInvoke(core.clj:5868)
17:41:49         at clojure.lang.RestFn.applyTo(RestFn.java:142)
17:41:49       at clojure.core$apply.invokeStatic(core.clj:659)
17:41:49    at clojure.core$load_libs.invokeStatic(core.clj:5925)
17:41:49    at clojure.core$load_libs.doInvoke(core.clj:5909)
17:41:49        at clojure.lang.RestFn.applyTo(RestFn.java:137)
17:41:49      at clojure.core$apply.invokeStatic(core.clj:659)
17:41:49   at clojure.core$require.invokeStatic(core.clj:5947)
17:41:49     at clojure.core$require.doInvoke(core.clj:5947)
17:41:49   at clojure.lang.RestFn.invoke(RestFn.java:3204)
17:41:49         at datastream.test.core$eval2198$loading__6434__auto____2199.invoke(datastream/test/core.clj:1)
17:41:49       at datastream.test.core$eval2198.invokeStatic(datastream/test/core.clj:1)
17:41:49   at datastream.test.core$eval2198.invoke(datastream/test/core.clj:1)
17:41:49     at clojure.lang.Compiler.eval(Compiler.java:7062)
17:41:49         at clojure.lang.Compiler.eval(Compiler.java:7051)
17:41:49     at clojure.lang.Compiler.eval(Compiler.java:7052)
17:41:49         at clojure.lang.Compiler.eval(Compiler.java:7025)
17:41:49     at clojure.core$eval.invokeStatic(core.clj:3206)
17:41:49          at clojure.core$eval.invoke(core.clj:3202)
17:41:49     at cloverage.instrument$instrument$fn__893$fn__894.invoke(instrument.clj:460)
17:41:49     at cloverage.instrument$instrument$fn__893.invoke(instrument.clj:458)
17:41:49     at cloverage.instrument$instrument.invokeStatic(instrument.clj:457)
17:41:49       at cloverage.instrument$instrument.invoke(instrument.clj:436)
17:41:49       at cloverage.coverage$run_main$fn__2016.invoke(coverage.clj:238)
17:41:49    at cloverage.coverage$run_main.invokeStatic(coverage.clj:233)
17:41:49    at cloverage.coverage$run_main.invoke(coverage.clj:183)
17:41:49          at cloverage.coverage$run_project.invokeStatic(coverage.clj:290)
17:41:49       at cloverage.coverage$run_project.doInvoke(coverage.clj:286)
17:41:49        at clojure.lang.RestFn.invoke(RestFn.java:410)
17:41:49       at user$eval2187.invokeStatic(form-init4025771764530416015.clj:1)
17:41:49   at user$eval2187.invoke(form-init4025771764530416015.clj:1)
17:41:49     at clojure.lang.Compiler.eval(Compiler.java:7062)
17:41:49         at clojure.lang.Compiler.eval(Compiler.java:7052)
17:41:49     at clojure.lang.Compiler.load(Compiler.java:7514)
17:41:49         ... 12 more
17:41:49  [Pipeline] }
17:41:50  WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succeeded?

Would you please let me know suggestions, if you have any?

Thanks in Advance
Balaji Sivaramgari

**Comment by winks** [comment]
Closing this, as there doesn't seem to be a problem in leiningen
