### ISSUE TITLE
'lein repl' fails with java.lang.ExceptionInInitializerError (macOS)

### ISSUE THREAD

**Issue by mdbergmann** [technomancy/leiningen#2667]
Below is the full stack trace.

System is macOS 10.15.3.
Java: JDK 8 / 11

`lein repl` throws the below exception.  
This happend in a project folder but also someplace else.

`lein version` or other commands still work.

`~/.lein` was cleaned up.

Downgrading Leiningen shows that 2.7.1 still works. Starts failing with 2.9.0.
Couldn't try 2.8 versions, not available in `sdkman`.

Stack trace:
```
~/Development/MySources/clj-gol (master ✘)✭ ᐅ lein repl
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2207)
	at clojure.lang.RT.classForName(RT.java:2216)
	at clojure.lang.RT.loadClassForName(RT.java:2235)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:2088)
	at leiningen.repl$loading__6706__auto____9794.invoke(repl.clj:1)
	at leiningen.repl__init.load(Unknown Source)
	at leiningen.repl__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2207)
	at clojure.lang.RT.classForName(RT.java:2216)
	at clojure.lang.RT.loadClassForName(RT.java:2235)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at leiningen.core.utils$require_resolve.invokeStatic(utils.clj:103)
	at leiningen.core.utils$require_resolve.invoke(utils.clj:96)
	at leiningen.core.utils$require_resolve.invokeStatic(utils.clj:106)
	at leiningen.core.utils$require_resolve.invoke(utils.clj:96)
	at leiningen.core.main$lookup_task_var.invokeStatic(main.clj:69)
	at leiningen.core.main$lookup_task_var.invoke(main.clj:65)
	at leiningen.core.main$pass_through_help_QMARK_.invokeStatic(main.clj:79)
	at leiningen.core.main$pass_through_help_QMARK_.invoke(main.clj:73)
	at leiningen.core.main$task_args.invokeStatic(main.clj:82)
	at leiningen.core.main$task_args.invoke(main.clj:81)
	at leiningen.core.main$resolve_and_apply.invokeStatic(main.clj:339)
	at leiningen.core.main$resolve_and_apply.invoke(main.clj:336)
	at leiningen.core.main$_main$fn__7445.invoke(main.clj:453)
	at leiningen.core.main$_main.invokeStatic(main.clj:442)
	at leiningen.core.main$_main.doInvoke(main.clj:439)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: EOF while reading
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.EdnReader.read(EdnReader.java:130)
	at clojure.lang.EdnReader.read(EdnReader.java:111)
	at clojure.edn$read.invokeStatic(edn.clj:35)
	at clojure.edn$read.invokeStatic(edn.clj:14)
	at clojure.edn$read.invoke(edn.clj:14)
	at nrepl.config$load_edn.invokeStatic(config.clj:36)
	at nrepl.config$load_edn.invoke(config.clj:32)
	at nrepl.config$load_config.invokeStatic(config.clj:45)
	at nrepl.config$load_config.invoke(config.clj:38)
	at nrepl.config__init.load(Unknown Source)
	at nrepl.config__init.<clinit>(Unknown Source)
	... 78 more
```

**Comment by mdbergmann** [comment]
It seems that for some treason I have an empty file `~/.nrepl/nrepl.edn` which causes this issue.
Removing this empty file `lein repl` seems to work fine.

There are still a few questions, why does it work with Leiningen 2.7.3 even if the file is empty?

**Comment by mdbergmann** [comment]
Maybe this empty file was an artefact from an earlier nrepl version.

For me this issues is resolved.

**Comment by technomancy** [comment]
Older versions of lein used `org.clojure/tools.nrepl` but now we use the standalone not-contrib `nrepl` dependency that supports being configured independently of Leiningen.
