### ISSUE TITLE
Same NoClasDefFoundError exception regardless of project I try to start

### ISSUE THREAD

**Issue by ExMateria** [technomancy/leiningen#676]
I'm a noob to everything(linux, clojure, emacs, vi etc.) trying to get a Debian VM set up from which to learn to develop a web app using web-noir or clojurescriptone, emacs, slime and datomic etc.. I'm on Debian squeeze, I've got JDK 7u5 installed. I've installed leiningen but when I go to use it, whether to try and get web-noir or clojurescriptone (really the only two I've tried--I'm really a super noob unfortunately) I end up with what appears to be (haven't looked beyond the  first couple lines for similarities) the same error for both programs.

I've looked up all I can find on the NoClassDefFoundError exception and virtually everyone seems to say it's a classpath issue. So I looked up how to modify my classpath (which I'd never done previously-noob in bash/linux) tried setting that to the directory in clojure that contained a file name that seemed to match the clojure.core.protocols$seq_reduce error, no luck [noobcomplaining] so since I'm new to this and about as close to my wits end as I've ever been trying to get to where i can learn clojure and get on actually working on my project, and I haven't managed on a solution after this last week's worth of 'spare-time' being consumed in this quest, so[/noobcomplaining] I thought I'd venture to ask. See if someone can point me in the right dirrection.

Here's the error when I was trying to run clojurescriptone. Again this appears to me to be the very same one I get when I try web-noir as well (this was after having installed lein 2.0.0-preview7) --

$:/bin/one# lein bootstrap

Exception in thread "main" java.lang.NoClassDefFoundError: clojure.core.protocols$seq_reduce
   at java.lang.Class.initializeClass(libgcj.so.10)
   at clojure.core.protocols__init.load(Unknown Source:19)
   at clojure.core.protocols__init.<clinit>(Unknown Source)
   at java.lang.Class.initializeClass(libgcj.so.10)
   at java.lang.Class.forName(libgcj.so.10)
   at clojure.lang.RT.loadClassForName(RT.java:2056)
   at clojure.lang.RT.load(RT.java:419)
   at clojure.lang.RT.load(RT.java:400)
   at clojure.core$load$fn__4890.invoke(core.clj:5415)
   at clojure.core$load.doInvoke(core.clj:5414)
   at clojure.lang.RestFn.invoke(RestFn.java:408)
   at clojure.core__init.load(Unknown Source:6010)
   at clojure.core__init.<clinit>(Unknown Source)
   at java.lang.Class.initializeClass(libgcj.so.10)
   at java.lang.Class.forName(libgcj.so.10)
   at clojure.lang.RT.loadClassForName(RT.java:2056)
   at clojure.lang.RT.load(RT.java:419)
   at clojure.lang.RT.load(RT.java:400)
   at clojure.lang.RT.doInit(RT.java:436)
   at clojure.lang.RT.<clinit>(RT.java:318)
   at java.lang.Class.initializeClass(libgcj.so.10)
   at clojure.main.<clinit>(main.java:20)
   at java.lang.Class.initializeClass(libgcj.so.10)
Caused by: java.lang.VerifyError: verification failed at PC 78 in clojure.core.protocols$seq_reduce:invoke((Ljava.lang.Object;Ljava.lang.Object;Ljava.lang.Object;)Ljava.lang.Object;): incompatible type on stack
   at java.lang.Class.initializeClass(libgcj.so.10)
   ...22 more

So what do you think?

Permissions issues? Path? Classpath? Fiendish flamingo eating munchkins?

**Comment by sudddenly** [comment]
http://www.freshblurbs.com/blog/2011/01/29/installing-and-configuring-clojure-centos-5.html
install java-1.6.0-openjdk-devel on centos6, problem sloved
